package com.druid.dao.mapper;

import com.druid.model.pojo.Entity;
import com.druid.model.pojo.EntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface EntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_entity
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    long countByExample(EntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_entity
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    int deleteByExample(EntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_entity
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    @Delete({
        "delete from t_entity",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_entity
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    @Insert({
        "insert into t_entity (name, crete_time, ",
        "update_time)",
        "values (#{name,jdbcType=VARCHAR}, #{creteTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_entity
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    int insertSelective(Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_entity
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    List<Entity> selectByExample(EntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_entity
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    @Select({
        "select",
        "id, name, crete_time, update_time",
        "from t_entity",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.druid.dao.mapper.EntityMapper.BaseResultMap")
    Entity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_entity
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    int updateByExampleSelective(@Param("record") Entity record, @Param("example") EntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_entity
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    int updateByExample(@Param("record") Entity record, @Param("example") EntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_entity
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    int updateByPrimaryKeySelective(Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_entity
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    @Update({
        "update t_entity",
        "set name = #{name,jdbcType=VARCHAR},",
          "crete_time = #{creteTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Entity record);
}