package com.shopstat.dao.mapper;

import com.shopstat.model.pojo.LodSafeguard;
import com.shopstat.model.pojo.LodSafeguardExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface LodSafeguardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lod_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    int countByExample(LodSafeguardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lod_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    int deleteByExample(LodSafeguardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lod_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    @Delete({
        "delete from lod_safeguard",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lod_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    @Insert({
        "insert into lod_safeguard (stat_date, insert_time, ",
        "safeguard_id, order_id, ",
        "from_source, order_amount, ",
        "product_id, tag_id, ",
        "sub_id, third_id, ",
        "apply_time, user_id, ",
        "shop_id, safeguard_state, ",
        "safeguard_starter, safeguard_reason, ",
        "mistaker, over_time)",
        "values (#{statDate,jdbcType=DATE}, #{insertTime,jdbcType=TIMESTAMP}, ",
        "#{safeguardId,jdbcType=BIGINT}, #{orderId,jdbcType=VARCHAR}, ",
        "#{fromSource,jdbcType=INTEGER}, #{orderAmount,jdbcType=BIGINT}, ",
        "#{productId,jdbcType=VARCHAR}, #{tagId,jdbcType=INTEGER}, ",
        "#{subId,jdbcType=INTEGER}, #{thirdId,jdbcType=INTEGER}, ",
        "#{applyTime,jdbcType=TIMESTAMP}, #{userId,jdbcType=BIGINT}, ",
        "#{shopId,jdbcType=BIGINT}, #{safeguardState,jdbcType=INTEGER}, ",
        "#{safeguardStarter,jdbcType=INTEGER}, #{safeguardReason,jdbcType=INTEGER}, ",
        "#{mistaker,jdbcType=INTEGER}, #{overTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(LodSafeguard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lod_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    int insertSelective(LodSafeguard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lod_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    List<LodSafeguard> selectByExample(LodSafeguardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lod_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    @Select({
        "select",
        "id, stat_date, insert_time, safeguard_id, order_id, from_source, order_amount, ",
        "product_id, tag_id, sub_id, third_id, apply_time, user_id, shop_id, safeguard_state, ",
        "safeguard_starter, safeguard_reason, mistaker, over_time",
        "from lod_safeguard",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    LodSafeguard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lod_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") LodSafeguard record, @Param("example") LodSafeguardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lod_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    int updateByExample(@Param("record") LodSafeguard record, @Param("example") LodSafeguardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lod_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    int updateByPrimaryKeySelective(LodSafeguard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lod_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    @Update({
        "update lod_safeguard",
        "set stat_date = #{statDate,jdbcType=DATE},",
          "insert_time = #{insertTime,jdbcType=TIMESTAMP},",
          "safeguard_id = #{safeguardId,jdbcType=BIGINT},",
          "order_id = #{orderId,jdbcType=VARCHAR},",
          "from_source = #{fromSource,jdbcType=INTEGER},",
          "order_amount = #{orderAmount,jdbcType=BIGINT},",
          "product_id = #{productId,jdbcType=VARCHAR},",
          "tag_id = #{tagId,jdbcType=INTEGER},",
          "sub_id = #{subId,jdbcType=INTEGER},",
          "third_id = #{thirdId,jdbcType=INTEGER},",
          "apply_time = #{applyTime,jdbcType=TIMESTAMP},",
          "user_id = #{userId,jdbcType=BIGINT},",
          "shop_id = #{shopId,jdbcType=BIGINT},",
          "safeguard_state = #{safeguardState,jdbcType=INTEGER},",
          "safeguard_starter = #{safeguardStarter,jdbcType=INTEGER},",
          "safeguard_reason = #{safeguardReason,jdbcType=INTEGER},",
          "mistaker = #{mistaker,jdbcType=INTEGER},",
          "over_time = #{overTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(LodSafeguard record);
}