package com.shopstat.dao.mapper;

import com.shopstat.model.pojo.StatSafeguard;
import com.shopstat.model.pojo.StatSafeguardExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface StatSafeguardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    int countByExample(StatSafeguardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    int deleteByExample(StatSafeguardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    @Delete({
        "delete from stat_safeguard",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    @Insert({
        "insert into stat_safeguard (stat_date, insert_time, ",
        "from_source, tag_id, ",
        "sub_id, third_id, ",
        "safeguard_starter, inc_cnt, ",
        "shop_mistake_cnt, user_mistake_cnt, ",
        "complete_cnt, complete_over_week_cnt, ",
        "close_cnt, dealing_total_cnt)",
        "values (#{statDate,jdbcType=DATE}, #{insertTime,jdbcType=TIMESTAMP}, ",
        "#{fromSource,jdbcType=INTEGER}, #{tagId,jdbcType=INTEGER}, ",
        "#{subId,jdbcType=INTEGER}, #{thirdId,jdbcType=INTEGER}, ",
        "#{safeguardStarter,jdbcType=INTEGER}, #{incCnt,jdbcType=INTEGER}, ",
        "#{shopMistakeCnt,jdbcType=INTEGER}, #{userMistakeCnt,jdbcType=INTEGER}, ",
        "#{completeCnt,jdbcType=INTEGER}, #{completeOverWeekCnt,jdbcType=INTEGER}, ",
        "#{closeCnt,jdbcType=INTEGER}, #{dealingTotalCnt,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(StatSafeguard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    int insertSelective(StatSafeguard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    List<StatSafeguard> selectByExample(StatSafeguardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    @Select({
        "select",
        "id, stat_date, insert_time, from_source, tag_id, sub_id, third_id, safeguard_starter, ",
        "inc_cnt, shop_mistake_cnt, user_mistake_cnt, complete_cnt, complete_over_week_cnt, ",
        "close_cnt, dealing_total_cnt",
        "from stat_safeguard",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    StatSafeguard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") StatSafeguard record, @Param("example") StatSafeguardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    int updateByExample(@Param("record") StatSafeguard record, @Param("example") StatSafeguardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    int updateByPrimaryKeySelective(StatSafeguard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_safeguard
     *
     * @mbggenerated Sat May 21 17:23:23 CST 2016
     */
    @Update({
        "update stat_safeguard",
        "set stat_date = #{statDate,jdbcType=DATE},",
          "insert_time = #{insertTime,jdbcType=TIMESTAMP},",
          "from_source = #{fromSource,jdbcType=INTEGER},",
          "tag_id = #{tagId,jdbcType=INTEGER},",
          "sub_id = #{subId,jdbcType=INTEGER},",
          "third_id = #{thirdId,jdbcType=INTEGER},",
          "safeguard_starter = #{safeguardStarter,jdbcType=INTEGER},",
          "inc_cnt = #{incCnt,jdbcType=INTEGER},",
          "shop_mistake_cnt = #{shopMistakeCnt,jdbcType=INTEGER},",
          "user_mistake_cnt = #{userMistakeCnt,jdbcType=INTEGER},",
          "complete_cnt = #{completeCnt,jdbcType=INTEGER},",
          "complete_over_week_cnt = #{completeOverWeekCnt,jdbcType=INTEGER},",
          "close_cnt = #{closeCnt,jdbcType=INTEGER},",
          "dealing_total_cnt = #{dealingTotalCnt,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(StatSafeguard record);
}