package com.micro.order.dao.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.micro.order.model.pojo.ShopOrder;
import com.micro.order.model.pojo.ShopOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ShopOrderMapper extends BaseMapper<ShopOrder>  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Thu May 30 15:45:36 CST 2019
     */
    int countByExample(ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Thu May 30 15:45:36 CST 2019
     */
    int deleteByExample(ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Thu May 30 15:45:36 CST 2019
     */
    @Delete({
        "delete from shop_order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Thu May 30 15:45:36 CST 2019
     */
    @Insert({
        "insert into shop_order (order_sn, buyer_id, ",
        "buyer_name, buyer_mobile, ",
        "statu, goods_id, goods_name, ",
        "goods_count, total_amount, ",
        "create_time, modified_time)",
        "values (#{orderSn,jdbcType=VARCHAR}, #{buyerId,jdbcType=BIGINT}, ",
        "#{buyerName,jdbcType=VARCHAR}, #{buyerMobile,jdbcType=VARCHAR}, ",
        "#{statu,jdbcType=INTEGER}, #{goodsId,jdbcType=BIGINT}, #{goodsName,jdbcType=VARCHAR}, ",
        "#{goodsCount,jdbcType=INTEGER}, #{totalAmount,jdbcType=BIGINT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{modifiedTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ShopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Thu May 30 15:45:36 CST 2019
     */
    int insertSelective(ShopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Thu May 30 15:45:36 CST 2019
     */
    List<ShopOrder> selectByExample(ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Thu May 30 15:45:36 CST 2019
     */
    @Select({
        "select",
        "id, order_sn, buyer_id, buyer_name, buyer_mobile, statu, goods_id, goods_name, ",
        "goods_count, total_amount, create_time, modified_time",
        "from shop_order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    ShopOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Thu May 30 15:45:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") ShopOrder record, @Param("example") ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Thu May 30 15:45:36 CST 2019
     */
    int updateByExample(@Param("record") ShopOrder record, @Param("example") ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Thu May 30 15:45:36 CST 2019
     */
    int updateByPrimaryKeySelective(ShopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Thu May 30 15:45:36 CST 2019
     */
    @Update({
        "update shop_order",
        "set order_sn = #{orderSn,jdbcType=VARCHAR},",
          "buyer_id = #{buyerId,jdbcType=BIGINT},",
          "buyer_name = #{buyerName,jdbcType=VARCHAR},",
          "buyer_mobile = #{buyerMobile,jdbcType=VARCHAR},",
          "statu = #{statu,jdbcType=INTEGER},",
          "goods_id = #{goodsId,jdbcType=BIGINT},",
          "goods_name = #{goodsName,jdbcType=VARCHAR},",
          "goods_count = #{goodsCount,jdbcType=INTEGER},",
          "total_amount = #{totalAmount,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modified_time = #{modifiedTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ShopOrder record);
}