package com.otd.boot.plat.model.entity;

import java.util.Date;

public class Factory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.id
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.factory_no
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    private String factoryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.factory_name
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    private String factoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.factory_address
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    private String factoryAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.legal_person
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    private String legalPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.create_time
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.create_by
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.update_time
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.update_by
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.id
     *
     * @return the value of factory.id
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.id
     *
     * @param id the value for factory.id
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.factory_no
     *
     * @return the value of factory.factory_no
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public String getFactoryNo() {
        return factoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.factory_no
     *
     * @param factoryNo the value for factory.factory_no
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public void setFactoryNo(String factoryNo) {
        this.factoryNo = factoryNo == null ? null : factoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.factory_name
     *
     * @return the value of factory.factory_name
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.factory_name
     *
     * @param factoryName the value for factory.factory_name
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName == null ? null : factoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.factory_address
     *
     * @return the value of factory.factory_address
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public String getFactoryAddress() {
        return factoryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.factory_address
     *
     * @param factoryAddress the value for factory.factory_address
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public void setFactoryAddress(String factoryAddress) {
        this.factoryAddress = factoryAddress == null ? null : factoryAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.legal_person
     *
     * @return the value of factory.legal_person
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.legal_person
     *
     * @param legalPerson the value for factory.legal_person
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson == null ? null : legalPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.create_time
     *
     * @return the value of factory.create_time
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.create_time
     *
     * @param createTime the value for factory.create_time
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.create_by
     *
     * @return the value of factory.create_by
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.create_by
     *
     * @param createBy the value for factory.create_by
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.update_time
     *
     * @return the value of factory.update_time
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.update_time
     *
     * @param updateTime the value for factory.update_time
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.update_by
     *
     * @return the value of factory.update_by
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.update_by
     *
     * @param updateBy the value for factory.update_by
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}