server:
  port: 8000

#actuator
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: ["health","info","beans","configprops","env","heapdump","threaddump","mappings","loggers","refresh"]

spring:
  application:
      name: rocketmq
  servlet:
      multipart:
          max-file-size: 100MB
          max-request-size: 500MB

###mq
rocketmq:
  namesrvAddr: localhost:9876
  producer:
    isOnOff: on
    maxMessageSize: 4096
    sendMsgTimeout: 3000
    retryTimesWhenSendFailed: 2
  consumer:
    isOnOff: on
    consumeThreadMin: 20
    consumeThreadMax: 64
    consumeMessageBatchMaxSize: 1

#日志
logging:
  level.root: info
  level.com.rocketmq: debug
  path: /data/logs
  config:
    classpath: logback-spring.xml