package com.commonservice.sms.dao.mapper;

import com.commonservice.sms.model.pojo.Sms;
import com.commonservice.sms.model.pojo.SmsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface SmsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated Fri Jun 01 10:38:54 CST 2018
     */
    int countByExample(SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated Fri Jun 01 10:38:54 CST 2018
     */
    int deleteByExample(SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated Fri Jun 01 10:38:54 CST 2018
     */
    @Delete({
        "delete from sms",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated Fri Jun 01 10:38:54 CST 2018
     */
    @Insert({
        "insert into sms (mobile, content, ",
        "captcha, send_time, ",
        "send_result, rt_code, ",
        "rt_message, biz_id, ",
        "type, fail_count, ",
        "verify_count, is_use, ",
        "expire_time, create_time, ",
        "modified_time)",
        "values (#{mobile,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{captcha,jdbcType=VARCHAR}, #{sendTime,jdbcType=TIMESTAMP}, ",
        "#{sendResult,jdbcType=INTEGER}, #{rtCode,jdbcType=VARCHAR}, ",
        "#{rtMessage,jdbcType=VARCHAR}, #{bizId,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=INTEGER}, #{failCount,jdbcType=INTEGER}, ",
        "#{verifyCount,jdbcType=INTEGER}, #{isUse,jdbcType=INTEGER}, ",
        "#{expireTime,jdbcType=TIMESTAMP}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{modifiedTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Sms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated Fri Jun 01 10:38:54 CST 2018
     */
    int insertSelective(Sms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated Fri Jun 01 10:38:54 CST 2018
     */
    List<Sms> selectByExample(SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated Fri Jun 01 10:38:54 CST 2018
     */
    @Select({
        "select",
        "id, mobile, content, captcha, send_time, send_result, rt_code, rt_message, biz_id, ",
        "type, fail_count, verify_count, is_use, expire_time, create_time, modified_time",
        "from sms",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Sms selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated Fri Jun 01 10:38:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sms record, @Param("example") SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated Fri Jun 01 10:38:54 CST 2018
     */
    int updateByExample(@Param("record") Sms record, @Param("example") SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated Fri Jun 01 10:38:54 CST 2018
     */
    int updateByPrimaryKeySelective(Sms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated Fri Jun 01 10:38:54 CST 2018
     */
    @Update({
        "update sms",
        "set mobile = #{mobile,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "captcha = #{captcha,jdbcType=VARCHAR},",
          "send_time = #{sendTime,jdbcType=TIMESTAMP},",
          "send_result = #{sendResult,jdbcType=INTEGER},",
          "rt_code = #{rtCode,jdbcType=VARCHAR},",
          "rt_message = #{rtMessage,jdbcType=VARCHAR},",
          "biz_id = #{bizId,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "fail_count = #{failCount,jdbcType=INTEGER},",
          "verify_count = #{verifyCount,jdbcType=INTEGER},",
          "is_use = #{isUse,jdbcType=INTEGER},",
          "expire_time = #{expireTime,jdbcType=TIMESTAMP},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modified_time = #{modifiedTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Sms record);
}