package com.shop.book.manage.dao.shop.mapper;

import com.shop.book.manage.model.pojo.shop.Advert;
import com.shop.book.manage.model.pojo.shop.AdvertExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface AdvertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Fri Dec 28 10:40:19 CST 2018
     */
    int countByExample(AdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Fri Dec 28 10:40:19 CST 2018
     */
    int deleteByExample(AdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Fri Dec 28 10:40:19 CST 2018
     */
    @Delete({
        "delete from advert",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Fri Dec 28 10:40:19 CST 2018
     */
    @Insert({
        "insert into advert (title, content, ",
        "statu, position_code, ",
        "position_name, img_url, ",
        "start_time, end_time, ",
        "sort, go_type, go_value, ",
        "create_time, modified_time)",
        "values (#{title,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{statu,jdbcType=INTEGER}, #{positionCode,jdbcType=VARCHAR}, ",
        "#{positionName,jdbcType=VARCHAR}, #{imgUrl,jdbcType=VARCHAR}, ",
        "#{startTime,jdbcType=TIMESTAMP}, #{endTime,jdbcType=TIMESTAMP}, ",
        "#{sort,jdbcType=INTEGER}, #{goType,jdbcType=INTEGER}, #{goValue,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{modifiedTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Advert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Fri Dec 28 10:40:19 CST 2018
     */
    int insertSelective(Advert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Fri Dec 28 10:40:19 CST 2018
     */
    List<Advert> selectByExample(AdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Fri Dec 28 10:40:19 CST 2018
     */
    @Select({
        "select",
        "id, title, content, statu, position_code, position_name, img_url, start_time, ",
        "end_time, sort, go_type, go_value, create_time, modified_time",
        "from advert",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Advert selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Fri Dec 28 10:40:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") Advert record, @Param("example") AdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Fri Dec 28 10:40:19 CST 2018
     */
    int updateByExample(@Param("record") Advert record, @Param("example") AdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Fri Dec 28 10:40:19 CST 2018
     */
    int updateByPrimaryKeySelective(Advert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Fri Dec 28 10:40:19 CST 2018
     */
    @Update({
        "update advert",
        "set title = #{title,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "statu = #{statu,jdbcType=INTEGER},",
          "position_code = #{positionCode,jdbcType=VARCHAR},",
          "position_name = #{positionName,jdbcType=VARCHAR},",
          "img_url = #{imgUrl,jdbcType=VARCHAR},",
          "start_time = #{startTime,jdbcType=TIMESTAMP},",
          "end_time = #{endTime,jdbcType=TIMESTAMP},",
          "sort = #{sort,jdbcType=INTEGER},",
          "go_type = #{goType,jdbcType=INTEGER},",
          "go_value = #{goValue,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modified_time = #{modifiedTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Advert record);
}