package com.shop.book.manage.dao.shop.mapper;

import com.shop.book.manage.model.pojo.shop.Dict;
import com.shop.book.manage.model.pojo.shop.DictExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface DictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbggenerated Fri Dec 28 13:48:45 CST 2018
     */
    int countByExample(DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbggenerated Fri Dec 28 13:48:45 CST 2018
     */
    int deleteByExample(DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbggenerated Fri Dec 28 13:48:45 CST 2018
     */
    @Delete({
        "delete from dict",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbggenerated Fri Dec 28 13:48:45 CST 2018
     */
    @Insert({
        "insert into dict (dict_key, dict_label, ",
        "dict_value, dict_ext, ",
        "dict_type, dict_type_name, ",
        "is_use, sort, create_time, ",
        "modified_time)",
        "values (#{dictKey,jdbcType=VARCHAR}, #{dictLabel,jdbcType=VARCHAR}, ",
        "#{dictValue,jdbcType=VARCHAR}, #{dictExt,jdbcType=VARCHAR}, ",
        "#{dictType,jdbcType=INTEGER}, #{dictTypeName,jdbcType=VARCHAR}, ",
        "#{isUse,jdbcType=INTEGER}, #{sort,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{modifiedTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbggenerated Fri Dec 28 13:48:45 CST 2018
     */
    int insertSelective(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbggenerated Fri Dec 28 13:48:45 CST 2018
     */
    List<Dict> selectByExample(DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbggenerated Fri Dec 28 13:48:45 CST 2018
     */
    @Select({
        "select",
        "id, dict_key, dict_label, dict_value, dict_ext, dict_type, dict_type_name, is_use, ",
        "sort, create_time, modified_time",
        "from dict",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Dict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbggenerated Fri Dec 28 13:48:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") Dict record, @Param("example") DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbggenerated Fri Dec 28 13:48:45 CST 2018
     */
    int updateByExample(@Param("record") Dict record, @Param("example") DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbggenerated Fri Dec 28 13:48:45 CST 2018
     */
    int updateByPrimaryKeySelective(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbggenerated Fri Dec 28 13:48:45 CST 2018
     */
    @Update({
        "update dict",
        "set dict_key = #{dictKey,jdbcType=VARCHAR},",
          "dict_label = #{dictLabel,jdbcType=VARCHAR},",
          "dict_value = #{dictValue,jdbcType=VARCHAR},",
          "dict_ext = #{dictExt,jdbcType=VARCHAR},",
          "dict_type = #{dictType,jdbcType=INTEGER},",
          "dict_type_name = #{dictTypeName,jdbcType=VARCHAR},",
          "is_use = #{isUse,jdbcType=INTEGER},",
          "sort = #{sort,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modified_time = #{modifiedTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Dict record);
}