server:
  port: 8080
  #context-path: /conf

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/manageplat?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    max-active: 60
    min-idle: 6
    max-wait: 20000
  mvc.static-path-pattern: /static/**             # resources
  resources.static-locations: classpath:/static/
# freemarker
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings.number_format: 0.##########

zookeeper:
    hosts: 127.0.0.1:2181
    sessionTimeout: 5000

#mybatisplus插件
mybatis-plus:
  typeAliasesPackage: com.bootmp.model
  mapper-locations: classpath*:sqlmap/**/*.xml
  global-config:
    db-config:
      id-type: 0
      logic-delete-value: 0
      logic-not-delete-value: 1
      table-prefix:
  configuration:
    map-underscore-to-camel-case: true

# mybatis
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

### xxl-conf, datasource
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xxl-conf?Unicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring.datasource.type=org.apache.tomcat.jdbc.pool.DataSource
spring.datasource.tomcat.max-wait=10000
spring.datasource.tomcat.max-active=30
spring.datasource.tomcat.test-on-borrow=true

# xxl-conf, confdata
xxl.conf.confdata.filepath=/data/applogs/xxl-conf/confdata
xxl.conf.access.token=

logging.level.com.bootmp.dao: debug