package com.shop.model.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShDiscountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    public ShDiscountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(Long value) {
            addCriterion("shop_id =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(Long value) {
            addCriterion("shop_id <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(Long value) {
            addCriterion("shop_id >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Long value) {
            addCriterion("shop_id >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(Long value) {
            addCriterion("shop_id <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Long value) {
            addCriterion("shop_id <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<Long> values) {
            addCriterion("shop_id in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<Long> values) {
            addCriterion("shop_id not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(Long value1, Long value2) {
            addCriterion("shop_id between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(Long value1, Long value2) {
            addCriterion("shop_id not between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andDiscountNameIsNull() {
            addCriterion("discount_name is null");
            return (Criteria) this;
        }

        public Criteria andDiscountNameIsNotNull() {
            addCriterion("discount_name is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountNameEqualTo(String value) {
            addCriterion("discount_name =", value, "discountName");
            return (Criteria) this;
        }

        public Criteria andDiscountNameNotEqualTo(String value) {
            addCriterion("discount_name <>", value, "discountName");
            return (Criteria) this;
        }

        public Criteria andDiscountNameGreaterThan(String value) {
            addCriterion("discount_name >", value, "discountName");
            return (Criteria) this;
        }

        public Criteria andDiscountNameGreaterThanOrEqualTo(String value) {
            addCriterion("discount_name >=", value, "discountName");
            return (Criteria) this;
        }

        public Criteria andDiscountNameLessThan(String value) {
            addCriterion("discount_name <", value, "discountName");
            return (Criteria) this;
        }

        public Criteria andDiscountNameLessThanOrEqualTo(String value) {
            addCriterion("discount_name <=", value, "discountName");
            return (Criteria) this;
        }

        public Criteria andDiscountNameLike(String value) {
            addCriterion("discount_name like", value, "discountName");
            return (Criteria) this;
        }

        public Criteria andDiscountNameNotLike(String value) {
            addCriterion("discount_name not like", value, "discountName");
            return (Criteria) this;
        }

        public Criteria andDiscountNameIn(List<String> values) {
            addCriterion("discount_name in", values, "discountName");
            return (Criteria) this;
        }

        public Criteria andDiscountNameNotIn(List<String> values) {
            addCriterion("discount_name not in", values, "discountName");
            return (Criteria) this;
        }

        public Criteria andDiscountNameBetween(String value1, String value2) {
            addCriterion("discount_name between", value1, value2, "discountName");
            return (Criteria) this;
        }

        public Criteria andDiscountNameNotBetween(String value1, String value2) {
            addCriterion("discount_name not between", value1, value2, "discountName");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNull() {
            addCriterion("begin_time is null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNotNull() {
            addCriterion("begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeEqualTo(Date value) {
            addCriterion("begin_time =", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotEqualTo(Date value) {
            addCriterion("begin_time <>", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThan(Date value) {
            addCriterion("begin_time >", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("begin_time >=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThan(Date value) {
            addCriterion("begin_time <", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("begin_time <=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIn(List<Date> values) {
            addCriterion("begin_time in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotIn(List<Date> values) {
            addCriterion("begin_time not in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeBetween(Date value1, Date value2) {
            addCriterion("begin_time between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("begin_time not between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andDiscountStateIsNull() {
            addCriterion("discount_state is null");
            return (Criteria) this;
        }

        public Criteria andDiscountStateIsNotNull() {
            addCriterion("discount_state is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountStateEqualTo(Integer value) {
            addCriterion("discount_state =", value, "discountState");
            return (Criteria) this;
        }

        public Criteria andDiscountStateNotEqualTo(Integer value) {
            addCriterion("discount_state <>", value, "discountState");
            return (Criteria) this;
        }

        public Criteria andDiscountStateGreaterThan(Integer value) {
            addCriterion("discount_state >", value, "discountState");
            return (Criteria) this;
        }

        public Criteria andDiscountStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("discount_state >=", value, "discountState");
            return (Criteria) this;
        }

        public Criteria andDiscountStateLessThan(Integer value) {
            addCriterion("discount_state <", value, "discountState");
            return (Criteria) this;
        }

        public Criteria andDiscountStateLessThanOrEqualTo(Integer value) {
            addCriterion("discount_state <=", value, "discountState");
            return (Criteria) this;
        }

        public Criteria andDiscountStateIn(List<Integer> values) {
            addCriterion("discount_state in", values, "discountState");
            return (Criteria) this;
        }

        public Criteria andDiscountStateNotIn(List<Integer> values) {
            addCriterion("discount_state not in", values, "discountState");
            return (Criteria) this;
        }

        public Criteria andDiscountStateBetween(Integer value1, Integer value2) {
            addCriterion("discount_state between", value1, value2, "discountState");
            return (Criteria) this;
        }

        public Criteria andDiscountStateNotBetween(Integer value1, Integer value2) {
            addCriterion("discount_state not between", value1, value2, "discountState");
            return (Criteria) this;
        }

        public Criteria andDiscountRangeIsNull() {
            addCriterion("discount_range is null");
            return (Criteria) this;
        }

        public Criteria andDiscountRangeIsNotNull() {
            addCriterion("discount_range is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountRangeEqualTo(Integer value) {
            addCriterion("discount_range =", value, "discountRange");
            return (Criteria) this;
        }

        public Criteria andDiscountRangeNotEqualTo(Integer value) {
            addCriterion("discount_range <>", value, "discountRange");
            return (Criteria) this;
        }

        public Criteria andDiscountRangeGreaterThan(Integer value) {
            addCriterion("discount_range >", value, "discountRange");
            return (Criteria) this;
        }

        public Criteria andDiscountRangeGreaterThanOrEqualTo(Integer value) {
            addCriterion("discount_range >=", value, "discountRange");
            return (Criteria) this;
        }

        public Criteria andDiscountRangeLessThan(Integer value) {
            addCriterion("discount_range <", value, "discountRange");
            return (Criteria) this;
        }

        public Criteria andDiscountRangeLessThanOrEqualTo(Integer value) {
            addCriterion("discount_range <=", value, "discountRange");
            return (Criteria) this;
        }

        public Criteria andDiscountRangeIn(List<Integer> values) {
            addCriterion("discount_range in", values, "discountRange");
            return (Criteria) this;
        }

        public Criteria andDiscountRangeNotIn(List<Integer> values) {
            addCriterion("discount_range not in", values, "discountRange");
            return (Criteria) this;
        }

        public Criteria andDiscountRangeBetween(Integer value1, Integer value2) {
            addCriterion("discount_range between", value1, value2, "discountRange");
            return (Criteria) this;
        }

        public Criteria andDiscountRangeNotBetween(Integer value1, Integer value2) {
            addCriterion("discount_range not between", value1, value2, "discountRange");
            return (Criteria) this;
        }

        public Criteria andDiscountProductsIsNull() {
            addCriterion("discount_products is null");
            return (Criteria) this;
        }

        public Criteria andDiscountProductsIsNotNull() {
            addCriterion("discount_products is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountProductsEqualTo(String value) {
            addCriterion("discount_products =", value, "discountProducts");
            return (Criteria) this;
        }

        public Criteria andDiscountProductsNotEqualTo(String value) {
            addCriterion("discount_products <>", value, "discountProducts");
            return (Criteria) this;
        }

        public Criteria andDiscountProductsGreaterThan(String value) {
            addCriterion("discount_products >", value, "discountProducts");
            return (Criteria) this;
        }

        public Criteria andDiscountProductsGreaterThanOrEqualTo(String value) {
            addCriterion("discount_products >=", value, "discountProducts");
            return (Criteria) this;
        }

        public Criteria andDiscountProductsLessThan(String value) {
            addCriterion("discount_products <", value, "discountProducts");
            return (Criteria) this;
        }

        public Criteria andDiscountProductsLessThanOrEqualTo(String value) {
            addCriterion("discount_products <=", value, "discountProducts");
            return (Criteria) this;
        }

        public Criteria andDiscountProductsLike(String value) {
            addCriterion("discount_products like", value, "discountProducts");
            return (Criteria) this;
        }

        public Criteria andDiscountProductsNotLike(String value) {
            addCriterion("discount_products not like", value, "discountProducts");
            return (Criteria) this;
        }

        public Criteria andDiscountProductsIn(List<String> values) {
            addCriterion("discount_products in", values, "discountProducts");
            return (Criteria) this;
        }

        public Criteria andDiscountProductsNotIn(List<String> values) {
            addCriterion("discount_products not in", values, "discountProducts");
            return (Criteria) this;
        }

        public Criteria andDiscountProductsBetween(String value1, String value2) {
            addCriterion("discount_products between", value1, value2, "discountProducts");
            return (Criteria) this;
        }

        public Criteria andDiscountProductsNotBetween(String value1, String value2) {
            addCriterion("discount_products not between", value1, value2, "discountProducts");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeIsNull() {
            addCriterion("discount_type is null");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeIsNotNull() {
            addCriterion("discount_type is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeEqualTo(Integer value) {
            addCriterion("discount_type =", value, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeNotEqualTo(Integer value) {
            addCriterion("discount_type <>", value, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeGreaterThan(Integer value) {
            addCriterion("discount_type >", value, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("discount_type >=", value, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeLessThan(Integer value) {
            addCriterion("discount_type <", value, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeLessThanOrEqualTo(Integer value) {
            addCriterion("discount_type <=", value, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeIn(List<Integer> values) {
            addCriterion("discount_type in", values, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeNotIn(List<Integer> values) {
            addCriterion("discount_type not in", values, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeBetween(Integer value1, Integer value2) {
            addCriterion("discount_type between", value1, value2, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("discount_type not between", value1, value2, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountRuleIsNull() {
            addCriterion("discount_rule is null");
            return (Criteria) this;
        }

        public Criteria andDiscountRuleIsNotNull() {
            addCriterion("discount_rule is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountRuleEqualTo(String value) {
            addCriterion("discount_rule =", value, "discountRule");
            return (Criteria) this;
        }

        public Criteria andDiscountRuleNotEqualTo(String value) {
            addCriterion("discount_rule <>", value, "discountRule");
            return (Criteria) this;
        }

        public Criteria andDiscountRuleGreaterThan(String value) {
            addCriterion("discount_rule >", value, "discountRule");
            return (Criteria) this;
        }

        public Criteria andDiscountRuleGreaterThanOrEqualTo(String value) {
            addCriterion("discount_rule >=", value, "discountRule");
            return (Criteria) this;
        }

        public Criteria andDiscountRuleLessThan(String value) {
            addCriterion("discount_rule <", value, "discountRule");
            return (Criteria) this;
        }

        public Criteria andDiscountRuleLessThanOrEqualTo(String value) {
            addCriterion("discount_rule <=", value, "discountRule");
            return (Criteria) this;
        }

        public Criteria andDiscountRuleLike(String value) {
            addCriterion("discount_rule like", value, "discountRule");
            return (Criteria) this;
        }

        public Criteria andDiscountRuleNotLike(String value) {
            addCriterion("discount_rule not like", value, "discountRule");
            return (Criteria) this;
        }

        public Criteria andDiscountRuleIn(List<String> values) {
            addCriterion("discount_rule in", values, "discountRule");
            return (Criteria) this;
        }

        public Criteria andDiscountRuleNotIn(List<String> values) {
            addCriterion("discount_rule not in", values, "discountRule");
            return (Criteria) this;
        }

        public Criteria andDiscountRuleBetween(String value1, String value2) {
            addCriterion("discount_rule between", value1, value2, "discountRule");
            return (Criteria) this;
        }

        public Criteria andDiscountRuleNotBetween(String value1, String value2) {
            addCriterion("discount_rule not between", value1, value2, "discountRule");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sh_discount
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 28 14:29:18 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sh_discount
     *
     * @mbggenerated Thu Apr 28 14:29:18 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}