package com.shop.model.pojo;

import java.util.Date;

public class ShopDiscount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_discount.id
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_discount.shop_id
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_discount.discount_name
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    private String discountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_discount.begin_time
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_discount.end_time
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_discount.discount_state
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    private Integer discountState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_discount.discount_range
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    private Integer discountRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_discount.discount_products
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    private String discountProducts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_discount.discount_type
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    private Integer discountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_discount.discount_rule
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    private String discountRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_discount.create_time
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_discount.update_time
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_discount.id
     *
     * @return the value of shop_discount.id
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_discount.id
     *
     * @param id the value for shop_discount.id
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_discount.shop_id
     *
     * @return the value of shop_discount.shop_id
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_discount.shop_id
     *
     * @param shopId the value for shop_discount.shop_id
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_discount.discount_name
     *
     * @return the value of shop_discount.discount_name
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public String getDiscountName() {
        return discountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_discount.discount_name
     *
     * @param discountName the value for shop_discount.discount_name
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public void setDiscountName(String discountName) {
        this.discountName = discountName == null ? null : discountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_discount.begin_time
     *
     * @return the value of shop_discount.begin_time
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_discount.begin_time
     *
     * @param beginTime the value for shop_discount.begin_time
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_discount.end_time
     *
     * @return the value of shop_discount.end_time
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_discount.end_time
     *
     * @param endTime the value for shop_discount.end_time
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_discount.discount_state
     *
     * @return the value of shop_discount.discount_state
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public Integer getDiscountState() {
        return discountState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_discount.discount_state
     *
     * @param discountState the value for shop_discount.discount_state
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public void setDiscountState(Integer discountState) {
        this.discountState = discountState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_discount.discount_range
     *
     * @return the value of shop_discount.discount_range
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public Integer getDiscountRange() {
        return discountRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_discount.discount_range
     *
     * @param discountRange the value for shop_discount.discount_range
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public void setDiscountRange(Integer discountRange) {
        this.discountRange = discountRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_discount.discount_products
     *
     * @return the value of shop_discount.discount_products
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public String getDiscountProducts() {
        return discountProducts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_discount.discount_products
     *
     * @param discountProducts the value for shop_discount.discount_products
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public void setDiscountProducts(String discountProducts) {
        this.discountProducts = discountProducts == null ? null : discountProducts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_discount.discount_type
     *
     * @return the value of shop_discount.discount_type
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public Integer getDiscountType() {
        return discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_discount.discount_type
     *
     * @param discountType the value for shop_discount.discount_type
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public void setDiscountType(Integer discountType) {
        this.discountType = discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_discount.discount_rule
     *
     * @return the value of shop_discount.discount_rule
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public String getDiscountRule() {
        return discountRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_discount.discount_rule
     *
     * @param discountRule the value for shop_discount.discount_rule
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public void setDiscountRule(String discountRule) {
        this.discountRule = discountRule == null ? null : discountRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_discount.create_time
     *
     * @return the value of shop_discount.create_time
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_discount.create_time
     *
     * @param createTime the value for shop_discount.create_time
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_discount.update_time
     *
     * @return the value of shop_discount.update_time
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_discount.update_time
     *
     * @param updateTime the value for shop_discount.update_time
     *
     * @mbggenerated Tue Apr 26 18:09:50 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}