package com.shop.order.dao.mapper;

import com.shop.order.model.pojo.OrderOperateRecord;
import com.shop.order.model.pojo.OrderOperateRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface OrderOperateRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_record
     *
     * @mbggenerated Thu Feb 08 17:16:06 CST 2018
     */
    int countByExample(OrderOperateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_record
     *
     * @mbggenerated Thu Feb 08 17:16:06 CST 2018
     */
    int deleteByExample(OrderOperateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_record
     *
     * @mbggenerated Thu Feb 08 17:16:06 CST 2018
     */
    @Delete({
        "delete from order_operate_record",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_record
     *
     * @mbggenerated Thu Feb 08 17:16:06 CST 2018
     */
    @Insert({
        "insert into order_operate_record (order_no, pre_statu, ",
        "cur_statu, operate_action, ",
        "operate_desc, operator_id, ",
        "operator_name, note, ",
        "create_time, modified_time)",
        "values (#{orderNo,jdbcType=VARCHAR}, #{preStatu,jdbcType=INTEGER}, ",
        "#{curStatu,jdbcType=INTEGER}, #{operateAction,jdbcType=INTEGER}, ",
        "#{operateDesc,jdbcType=VARCHAR}, #{operatorId,jdbcType=BIGINT}, ",
        "#{operatorName,jdbcType=VARCHAR}, #{note,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{modifiedTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(OrderOperateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_record
     *
     * @mbggenerated Thu Feb 08 17:16:06 CST 2018
     */
    int insertSelective(OrderOperateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_record
     *
     * @mbggenerated Thu Feb 08 17:16:06 CST 2018
     */
    List<OrderOperateRecord> selectByExample(OrderOperateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_record
     *
     * @mbggenerated Thu Feb 08 17:16:06 CST 2018
     */
    @Select({
        "select",
        "id, order_no, pre_statu, cur_statu, operate_action, operate_desc, operator_id, ",
        "operator_name, note, create_time, modified_time",
        "from order_operate_record",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    OrderOperateRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_record
     *
     * @mbggenerated Thu Feb 08 17:16:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderOperateRecord record, @Param("example") OrderOperateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_record
     *
     * @mbggenerated Thu Feb 08 17:16:06 CST 2018
     */
    int updateByExample(@Param("record") OrderOperateRecord record, @Param("example") OrderOperateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_record
     *
     * @mbggenerated Thu Feb 08 17:16:06 CST 2018
     */
    int updateByPrimaryKeySelective(OrderOperateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_record
     *
     * @mbggenerated Thu Feb 08 17:16:06 CST 2018
     */
    @Update({
        "update order_operate_record",
        "set order_no = #{orderNo,jdbcType=VARCHAR},",
          "pre_statu = #{preStatu,jdbcType=INTEGER},",
          "cur_statu = #{curStatu,jdbcType=INTEGER},",
          "operate_action = #{operateAction,jdbcType=INTEGER},",
          "operate_desc = #{operateDesc,jdbcType=VARCHAR},",
          "operator_id = #{operatorId,jdbcType=BIGINT},",
          "operator_name = #{operatorName,jdbcType=VARCHAR},",
          "note = #{note,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modified_time = #{modifiedTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OrderOperateRecord record);
}