package com.shop.user.dao.mapper;

import com.shop.user.model.pojo.ShopUser;
import com.shop.user.model.pojo.ShopUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ShopUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Wed Jul 04 09:43:43 CST 2018
     */
    int countByExample(ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Wed Jul 04 09:43:43 CST 2018
     */
    int deleteByExample(ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Wed Jul 04 09:43:43 CST 2018
     */
    @Delete({
        "delete from shop_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Wed Jul 04 09:43:43 CST 2018
     */
    @Insert({
        "insert into shop_user (name, nick_name, ",
        "sex, mobile, statu, ",
        "reg_comefrom, reg_time, ",
        "last_login_id, last_login_time, ",
        "token, token_expire_time, ",
        "app, app_version, ",
        "device_os, device_os_version, ",
        "device_token, create_time, ",
        "modified_time)",
        "values (#{name,jdbcType=VARCHAR}, #{nickName,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=INTEGER}, #{mobile,jdbcType=VARCHAR}, #{statu,jdbcType=INTEGER}, ",
        "#{regComefrom,jdbcType=INTEGER}, #{regTime,jdbcType=TIMESTAMP}, ",
        "#{lastLoginId,jdbcType=BIGINT}, #{lastLoginTime,jdbcType=TIMESTAMP}, ",
        "#{token,jdbcType=VARCHAR}, #{tokenExpireTime,jdbcType=TIMESTAMP}, ",
        "#{app,jdbcType=VARCHAR}, #{appVersion,jdbcType=VARCHAR}, ",
        "#{deviceOs,jdbcType=VARCHAR}, #{deviceOsVersion,jdbcType=VARCHAR}, ",
        "#{deviceToken,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{modifiedTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ShopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Wed Jul 04 09:43:43 CST 2018
     */
    int insertSelective(ShopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Wed Jul 04 09:43:43 CST 2018
     */
    List<ShopUser> selectByExample(ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Wed Jul 04 09:43:43 CST 2018
     */
    @Select({
        "select",
        "id, name, nick_name, sex, mobile, statu, reg_comefrom, reg_time, last_login_id, ",
        "last_login_time, token, token_expire_time, app, app_version, device_os, device_os_version, ",
        "device_token, create_time, modified_time",
        "from shop_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    ShopUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Wed Jul 04 09:43:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopUser record, @Param("example") ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Wed Jul 04 09:43:43 CST 2018
     */
    int updateByExample(@Param("record") ShopUser record, @Param("example") ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Wed Jul 04 09:43:43 CST 2018
     */
    int updateByPrimaryKeySelective(ShopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Wed Jul 04 09:43:43 CST 2018
     */
    @Update({
        "update shop_user",
        "set name = #{name,jdbcType=VARCHAR},",
          "nick_name = #{nickName,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=INTEGER},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "statu = #{statu,jdbcType=INTEGER},",
          "reg_comefrom = #{regComefrom,jdbcType=INTEGER},",
          "reg_time = #{regTime,jdbcType=TIMESTAMP},",
          "last_login_id = #{lastLoginId,jdbcType=BIGINT},",
          "last_login_time = #{lastLoginTime,jdbcType=TIMESTAMP},",
          "token = #{token,jdbcType=VARCHAR},",
          "token_expire_time = #{tokenExpireTime,jdbcType=TIMESTAMP},",
          "app = #{app,jdbcType=VARCHAR},",
          "app_version = #{appVersion,jdbcType=VARCHAR},",
          "device_os = #{deviceOs,jdbcType=VARCHAR},",
          "device_os_version = #{deviceOsVersion,jdbcType=VARCHAR},",
          "device_token = #{deviceToken,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modified_time = #{modifiedTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ShopUser record);
}