spring:
  profiles:
    active: dev
  application:
    name: otdboot-demo-jsp
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    static-path-pattern: /resources/**
    pathmatch:
      matching-strategy: ant_path_matcher