package com.druid.model.pojo;

import java.util.Date;

public class Entity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_entity.id
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_entity.name
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_entity.crete_time
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    private Date creteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_entity.update_time
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_entity.id
     *
     * @return the value of t_entity.id
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_entity.id
     *
     * @param id the value for t_entity.id
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_entity.name
     *
     * @return the value of t_entity.name
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_entity.name
     *
     * @param name the value for t_entity.name
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_entity.crete_time
     *
     * @return the value of t_entity.crete_time
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    public Date getCreteTime() {
        return creteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_entity.crete_time
     *
     * @param creteTime the value for t_entity.crete_time
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    public void setCreteTime(Date creteTime) {
        this.creteTime = creteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_entity.update_time
     *
     * @return the value of t_entity.update_time
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_entity.update_time
     *
     * @param updateTime the value for t_entity.update_time
     *
     * @mbg.generated Thu Mar 16 10:11:02 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}