package com.mybatis.dao.mapper;

import com.mybatis.model.entity.Cache;
import com.mybatis.model.entity.CacheExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface CacheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cache
     *
     * @mbg.generated Tue Aug 22 14:08:14 CST 2023
     */
    long countByExample(CacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cache
     *
     * @mbg.generated Tue Aug 22 14:08:14 CST 2023
     */
    int deleteByExample(CacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cache
     *
     * @mbg.generated Tue Aug 22 14:08:14 CST 2023
     */
    @Delete({
        "delete from t_cache",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cache
     *
     * @mbg.generated Tue Aug 22 14:08:14 CST 2023
     */
    @Insert({
        "insert into t_cache (cache_name, sql_text, ",
        "sys, flag, remark)",
        "values (#{cacheName,jdbcType=VARCHAR}, #{sqlText,jdbcType=VARCHAR}, ",
        "#{sys,jdbcType=VARCHAR}, #{flag,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Cache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cache
     *
     * @mbg.generated Tue Aug 22 14:08:14 CST 2023
     */
    int insertSelective(Cache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cache
     *
     * @mbg.generated Tue Aug 22 14:08:14 CST 2023
     */
    List<Cache> selectByExample(CacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cache
     *
     * @mbg.generated Tue Aug 22 14:08:14 CST 2023
     */
    @Select({
        "select",
        "id, cache_name, sql_text, sys, flag, remark",
        "from t_cache",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.mybatis.dao.mapper.CacheMapper.BaseResultMap")
    Cache selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cache
     *
     * @mbg.generated Tue Aug 22 14:08:14 CST 2023
     */
    int updateByExampleSelective(@Param("record") Cache record, @Param("example") CacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cache
     *
     * @mbg.generated Tue Aug 22 14:08:14 CST 2023
     */
    int updateByExample(@Param("record") Cache record, @Param("example") CacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cache
     *
     * @mbg.generated Tue Aug 22 14:08:14 CST 2023
     */
    int updateByPrimaryKeySelective(Cache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cache
     *
     * @mbg.generated Tue Aug 22 14:08:14 CST 2023
     */
    @Update({
        "update t_cache",
        "set cache_name = #{cacheName,jdbcType=VARCHAR},",
          "sql_text = #{sqlText,jdbcType=VARCHAR},",
          "sys = #{sys,jdbcType=VARCHAR},",
          "flag = #{flag,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Cache record);
}