package com.mybatis.dao.mapper;

import com.mybatis.model.entity.CacheTable;
import com.mybatis.model.entity.CacheTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CacheTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cachetable
     *
     * @mbg.generated Tue Aug 22 16:18:07 CST 2023
     */
    long countByExample(CacheTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cachetable
     *
     * @mbg.generated Tue Aug 22 16:18:07 CST 2023
     */
    int deleteByExample(CacheTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cachetable
     *
     * @mbg.generated Tue Aug 22 16:18:07 CST 2023
     */
    @Delete({
        "delete from cachetable",
        "where cacheName = #{cachename,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String cachename);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cachetable
     *
     * @mbg.generated Tue Aug 22 16:18:07 CST 2023
     */
    @Insert({
        "insert into cachetable (cacheName, sqlText, ",
        "className, system, ",
        "flag, remark)",
        "values (#{cachename,jdbcType=VARCHAR}, #{sqltext,jdbcType=VARCHAR}, ",
        "#{classname,jdbcType=VARCHAR}, #{system,jdbcType=VARCHAR}, ",
        "#{flag,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(CacheTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cachetable
     *
     * @mbg.generated Tue Aug 22 16:18:07 CST 2023
     */
    int insertSelective(CacheTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cachetable
     *
     * @mbg.generated Tue Aug 22 16:18:07 CST 2023
     */
    List<CacheTable> selectByExample(CacheTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cachetable
     *
     * @mbg.generated Tue Aug 22 16:18:07 CST 2023
     */
    @Select({
        "select",
        "cacheName, sqlText, className, system, flag, remark",
        "from cachetable",
        "where cacheName = #{cachename,jdbcType=VARCHAR}"
    })
    @ResultMap("com.mybatis.dao.mapper.CacheTableMapper.BaseResultMap")
    CacheTable selectByPrimaryKey(String cachename);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cachetable
     *
     * @mbg.generated Tue Aug 22 16:18:07 CST 2023
     */
    int updateByExampleSelective(@Param("record") CacheTable record, @Param("example") CacheTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cachetable
     *
     * @mbg.generated Tue Aug 22 16:18:07 CST 2023
     */
    int updateByExample(@Param("record") CacheTable record, @Param("example") CacheTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cachetable
     *
     * @mbg.generated Tue Aug 22 16:18:07 CST 2023
     */
    int updateByPrimaryKeySelective(CacheTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cachetable
     *
     * @mbg.generated Tue Aug 22 16:18:07 CST 2023
     */
    @Update({
        "update cachetable",
        "set sqlText = #{sqltext,jdbcType=VARCHAR},",
          "className = #{classname,jdbcType=VARCHAR},",
          "system = #{system,jdbcType=VARCHAR},",
          "flag = #{flag,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where cacheName = #{cachename,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(CacheTable record);
}