package com.mybatis.dao.mapper;

import com.mybatis.model.entity.Data;
import com.mybatis.model.entity.DataExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface DataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbg.generated Tue Aug 22 14:23:55 CST 2023
     */
    long countByExample(DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbg.generated Tue Aug 22 14:23:55 CST 2023
     */
    int deleteByExample(DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbg.generated Tue Aug 22 14:23:55 CST 2023
     */
    @Delete({
        "delete from t_data",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbg.generated Tue Aug 22 14:23:55 CST 2023
     */
    @Insert({
        "insert into t_data (type, data, ",
        "fmt, remark, create_time, ",
        "create_by, update_time, ",
        "update_by)",
        "values (#{type,jdbcType=INTEGER}, #{data,jdbcType=VARCHAR}, ",
        "#{fmt,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{createBy,jdbcType=VARCHAR}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{updateBy,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbg.generated Tue Aug 22 14:23:55 CST 2023
     */
    int insertSelective(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbg.generated Tue Aug 22 14:23:55 CST 2023
     */
    List<Data> selectByExample(DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbg.generated Tue Aug 22 14:23:55 CST 2023
     */
    @Select({
        "select",
        "id, type, data, fmt, remark, create_time, create_by, update_time, update_by",
        "from t_data",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.mybatis.dao.mapper.DataMapper.BaseResultMap")
    Data selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbg.generated Tue Aug 22 14:23:55 CST 2023
     */
    int updateByExampleSelective(@Param("record") Data record, @Param("example") DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbg.generated Tue Aug 22 14:23:55 CST 2023
     */
    int updateByExample(@Param("record") Data record, @Param("example") DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbg.generated Tue Aug 22 14:23:55 CST 2023
     */
    int updateByPrimaryKeySelective(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbg.generated Tue Aug 22 14:23:55 CST 2023
     */
    @Update({
        "update t_data",
        "set type = #{type,jdbcType=INTEGER},",
          "data = #{data,jdbcType=VARCHAR},",
          "fmt = #{fmt,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_by = #{createBy,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Data record);
}