package com.storefront.manage.dao.mapper;

import com.storefront.manage.model.pojo.Brand;
import com.storefront.manage.model.pojo.BrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int countByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int deleteByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    @Delete({
        "delete from brand",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    @Insert({
        "insert into brand (name, first_idstry_code, ",
        "first_idstry_name, direct_idstry_code, ",
        "direct_idstry_name, is_idstry_mark, ",
        "company_id, is_jingying, ",
        "create_time, modified_time)",
        "values (#{name,jdbcType=VARCHAR}, #{firstIdstryCode,jdbcType=VARCHAR}, ",
        "#{firstIdstryName,jdbcType=VARCHAR}, #{directIdstryCode,jdbcType=VARCHAR}, ",
        "#{directIdstryName,jdbcType=VARCHAR}, #{isIdstryMark,jdbcType=INTEGER}, ",
        "#{companyId,jdbcType=BIGINT}, #{isJingying,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{modifiedTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int insertSelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    List<Brand> selectByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    @Select({
        "select",
        "id, name, first_idstry_code, first_idstry_name, direct_idstry_code, direct_idstry_name, ",
        "is_idstry_mark, company_id, is_jingying, create_time, modified_time",
        "from brand",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Brand selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int updateByExample(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int updateByPrimaryKeySelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    @Update({
        "update brand",
        "set name = #{name,jdbcType=VARCHAR},",
          "first_idstry_code = #{firstIdstryCode,jdbcType=VARCHAR},",
          "first_idstry_name = #{firstIdstryName,jdbcType=VARCHAR},",
          "direct_idstry_code = #{directIdstryCode,jdbcType=VARCHAR},",
          "direct_idstry_name = #{directIdstryName,jdbcType=VARCHAR},",
          "is_idstry_mark = #{isIdstryMark,jdbcType=INTEGER},",
          "company_id = #{companyId,jdbcType=BIGINT},",
          "is_jingying = #{isJingying,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modified_time = #{modifiedTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Brand record);
}