package com.storefront.manage.dao.mapper;

import com.storefront.manage.model.pojo.Industry;
import com.storefront.manage.model.pojo.IndustryExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface IndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int countByExample(IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int deleteByExample(IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    @Delete({
        "delete from industry",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    @Insert({
        "insert into industry (code, name, ",
        "level, parent_code, ",
        "parent_name, full_path, ",
        "create_time, modified_time)",
        "values (#{code,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{level,jdbcType=INTEGER}, #{parentCode,jdbcType=VARCHAR}, ",
        "#{parentName,jdbcType=VARCHAR}, #{fullPath,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{modifiedTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int insertSelective(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    List<Industry> selectByExample(IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    @Select({
        "select",
        "id, code, name, level, parent_code, parent_name, full_path, create_time, modified_time",
        "from industry",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Industry selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") Industry record, @Param("example") IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int updateByExample(@Param("record") Industry record, @Param("example") IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int updateByPrimaryKeySelective(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    @Update({
        "update industry",
        "set code = #{code,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "level = #{level,jdbcType=INTEGER},",
          "parent_code = #{parentCode,jdbcType=VARCHAR},",
          "parent_name = #{parentName,jdbcType=VARCHAR},",
          "full_path = #{fullPath,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modified_time = #{modifiedTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Industry record);
}