package com.storefront.manage.dao.mapper;

import com.storefront.manage.model.pojo.Store;
import com.storefront.manage.model.pojo.StoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int countByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int deleteByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    @Delete({
        "delete from store",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    @Insert({
        "insert into store (name, info, ",
        "is_business_mark, first_idstry_code, ",
        "first_idstry_name, direct_idstry_code, ",
        "direct_idstry_name, is_jingying, ",
        "is_jiameng, brand_id, ",
        "brand_name, start_time, ",
        "end_time, province_code, ",
        "province_name, city_code, ",
        "city_name, area_code, ",
        "area_name, position_name, ",
        "position_type, street_name, ",
        "detail_address, create_time, ",
        "modified_time)",
        "values (#{name,jdbcType=VARCHAR}, #{info,jdbcType=VARCHAR}, ",
        "#{isBusinessMark,jdbcType=INTEGER}, #{firstIdstryCode,jdbcType=VARCHAR}, ",
        "#{firstIdstryName,jdbcType=VARCHAR}, #{directIdstryCode,jdbcType=VARCHAR}, ",
        "#{directIdstryName,jdbcType=VARCHAR}, #{isJingying,jdbcType=INTEGER}, ",
        "#{isJiameng,jdbcType=INTEGER}, #{brandId,jdbcType=BIGINT}, ",
        "#{brandName,jdbcType=VARCHAR}, #{startTime,jdbcType=DATE}, ",
        "#{endTime,jdbcType=DATE}, #{provinceCode,jdbcType=VARCHAR}, ",
        "#{provinceName,jdbcType=VARCHAR}, #{cityCode,jdbcType=VARCHAR}, ",
        "#{cityName,jdbcType=VARCHAR}, #{areaCode,jdbcType=VARCHAR}, ",
        "#{areaName,jdbcType=VARCHAR}, #{positionName,jdbcType=VARCHAR}, ",
        "#{positionType,jdbcType=INTEGER}, #{streetName,jdbcType=VARCHAR}, ",
        "#{detailAddress,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{modifiedTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int insertSelective(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    List<Store> selectByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    @Select({
        "select",
        "id, name, info, is_business_mark, first_idstry_code, first_idstry_name, direct_idstry_code, ",
        "direct_idstry_name, is_jingying, is_jiameng, brand_id, brand_name, start_time, ",
        "end_time, province_code, province_name, city_code, city_name, area_code, area_name, ",
        "position_name, position_type, street_name, detail_address, create_time, modified_time",
        "from store",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Store selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") Store record, @Param("example") StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int updateByExample(@Param("record") Store record, @Param("example") StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    int updateByPrimaryKeySelective(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Tue May 07 16:01:34 CST 2019
     */
    @Update({
        "update store",
        "set name = #{name,jdbcType=VARCHAR},",
          "info = #{info,jdbcType=VARCHAR},",
          "is_business_mark = #{isBusinessMark,jdbcType=INTEGER},",
          "first_idstry_code = #{firstIdstryCode,jdbcType=VARCHAR},",
          "first_idstry_name = #{firstIdstryName,jdbcType=VARCHAR},",
          "direct_idstry_code = #{directIdstryCode,jdbcType=VARCHAR},",
          "direct_idstry_name = #{directIdstryName,jdbcType=VARCHAR},",
          "is_jingying = #{isJingying,jdbcType=INTEGER},",
          "is_jiameng = #{isJiameng,jdbcType=INTEGER},",
          "brand_id = #{brandId,jdbcType=BIGINT},",
          "brand_name = #{brandName,jdbcType=VARCHAR},",
          "start_time = #{startTime,jdbcType=DATE},",
          "end_time = #{endTime,jdbcType=DATE},",
          "province_code = #{provinceCode,jdbcType=VARCHAR},",
          "province_name = #{provinceName,jdbcType=VARCHAR},",
          "city_code = #{cityCode,jdbcType=VARCHAR},",
          "city_name = #{cityName,jdbcType=VARCHAR},",
          "area_code = #{areaCode,jdbcType=VARCHAR},",
          "area_name = #{areaName,jdbcType=VARCHAR},",
          "position_name = #{positionName,jdbcType=VARCHAR},",
          "position_type = #{positionType,jdbcType=INTEGER},",
          "street_name = #{streetName,jdbcType=VARCHAR},",
          "detail_address = #{detailAddress,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modified_time = #{modifiedTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Store record);
}