package com.shop.web.dao.mapper;

import com.shop.web.model.pojo.SfBrand;
import com.shop.web.model.pojo.SfBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface SfBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_brand
     *
     * @mbggenerated Sun Nov 19 16:13:49 CST 2017
     */
    int countByExample(SfBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_brand
     *
     * @mbggenerated Sun Nov 19 16:13:49 CST 2017
     */
    int deleteByExample(SfBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_brand
     *
     * @mbggenerated Sun Nov 19 16:13:49 CST 2017
     */
    @Delete({
        "delete from sf_brand",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_brand
     *
     * @mbggenerated Sun Nov 19 16:13:49 CST 2017
     */
    @Insert({
        "insert into sf_brand (name, logo, ",
        "level, is_show, sort, ",
        "create_time, update_time, ",
        "note)",
        "values (#{name,jdbcType=VARCHAR}, #{logo,jdbcType=VARCHAR}, ",
        "#{level,jdbcType=INTEGER}, #{isShow,jdbcType=INTEGER}, #{sort,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{note,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(SfBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_brand
     *
     * @mbggenerated Sun Nov 19 16:13:49 CST 2017
     */
    int insertSelective(SfBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_brand
     *
     * @mbggenerated Sun Nov 19 16:13:49 CST 2017
     */
    List<SfBrand> selectByExample(SfBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_brand
     *
     * @mbggenerated Sun Nov 19 16:13:49 CST 2017
     */
    @Select({
        "select",
        "id, name, logo, level, is_show, sort, create_time, update_time, note",
        "from sf_brand",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    SfBrand selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_brand
     *
     * @mbggenerated Sun Nov 19 16:13:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") SfBrand record, @Param("example") SfBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_brand
     *
     * @mbggenerated Sun Nov 19 16:13:49 CST 2017
     */
    int updateByExample(@Param("record") SfBrand record, @Param("example") SfBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_brand
     *
     * @mbggenerated Sun Nov 19 16:13:49 CST 2017
     */
    int updateByPrimaryKeySelective(SfBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_brand
     *
     * @mbggenerated Sun Nov 19 16:13:49 CST 2017
     */
    @Update({
        "update sf_brand",
        "set name = #{name,jdbcType=VARCHAR},",
          "logo = #{logo,jdbcType=VARCHAR},",
          "level = #{level,jdbcType=INTEGER},",
          "is_show = #{isShow,jdbcType=INTEGER},",
          "sort = #{sort,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "note = #{note,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SfBrand record);
}