package com.datastore.mysql.dao.mapper;

import com.datastore.mysql.model.entity.Resource;
import com.datastore.mysql.model.entity.ResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Apr 03 18:06:34 CST 2022
     */
    int countByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Apr 03 18:06:34 CST 2022
     */
    int deleteByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Apr 03 18:06:34 CST 2022
     */
    @Delete({
        "delete from sys_resource",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Apr 03 18:06:34 CST 2022
     */
    @Insert({
        "insert into sys_resource (name, parent_id, ",
        "is_show, tag, path, ",
        "icon, type, sort, ",
        "create_time, modify_time)",
        "values (#{name,jdbcType=VARCHAR}, #{parentId,jdbcType=INTEGER}, ",
        "#{isShow,jdbcType=INTEGER}, #{tag,jdbcType=VARCHAR}, #{path,jdbcType=VARCHAR}, ",
        "#{icon,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, #{sort,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{modifyTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Apr 03 18:06:34 CST 2022
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Apr 03 18:06:34 CST 2022
     */
    List<Resource> selectByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Apr 03 18:06:34 CST 2022
     */
    @Select({
        "select",
        "id, name, parent_id, is_show, tag, path, icon, type, sort, create_time, modify_time",
        "from sys_resource",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Resource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Apr 03 18:06:34 CST 2022
     */
    int updateByExampleSelective(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Apr 03 18:06:34 CST 2022
     */
    int updateByExample(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Apr 03 18:06:34 CST 2022
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Apr 03 18:06:34 CST 2022
     */
    @Update({
        "update sys_resource",
        "set name = #{name,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=INTEGER},",
          "is_show = #{isShow,jdbcType=INTEGER},",
          "tag = #{tag,jdbcType=VARCHAR},",
          "path = #{path,jdbcType=VARCHAR},",
          "icon = #{icon,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "sort = #{sort,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modify_time = #{modifyTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Resource record);
}