package com.micro.course.model.pojo;

import com.micro.course.model.BasePojo;
import java.util.Date;

public class UserCourse extends BasePojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.id
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.user_id
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.user_name
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.course_id
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    private Long courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.course_name
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.course_item_id
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    private Long courseItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.create_time
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.modified_time
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.id
     *
     * @return the value of user_course.id
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.id
     *
     * @param id the value for user_course.id
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.user_id
     *
     * @return the value of user_course.user_id
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.user_id
     *
     * @param userId the value for user_course.user_id
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.user_name
     *
     * @return the value of user_course.user_name
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.user_name
     *
     * @param userName the value for user_course.user_name
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.course_id
     *
     * @return the value of user_course.course_id
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.course_id
     *
     * @param courseId the value for user_course.course_id
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.course_name
     *
     * @return the value of user_course.course_name
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.course_name
     *
     * @param courseName the value for user_course.course_name
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.course_item_id
     *
     * @return the value of user_course.course_item_id
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public Long getCourseItemId() {
        return courseItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.course_item_id
     *
     * @param courseItemId the value for user_course.course_item_id
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public void setCourseItemId(Long courseItemId) {
        this.courseItemId = courseItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.create_time
     *
     * @return the value of user_course.create_time
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.create_time
     *
     * @param createTime the value for user_course.create_time
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.modified_time
     *
     * @return the value of user_course.modified_time
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.modified_time
     *
     * @param modifiedTime the value for user_course.modified_time
     *
     * @mbggenerated Thu May 23 10:27:19 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}