server:
  port: 8090

# Dubbo config
dubbo:
  application:
    id: manage-rbac-dubbo
    name: manage-rbac-dubbo
    version: 1.0.0
  protocol:
    name: dubbo
    port: 20890
  registry:
    protocol: zookeeper
    address: 192.168.0.54:2181
  consumer:
    version: 1.0.0
    check: false

logging:
  path: /data/logs
  filePrefix: manage-rbac-dubbo

spring:
  datasource:
    url: jdbc:mysql://rm-wz91qyhz4u3n7rw677o.mysql.rds.aliyuncs.com:3306/db_rbac?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: uurbac
    password: rbac000!
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20        #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      minimum-idle: 10             #连接池最小连接数
      connection-timeout: 30000    #连接超时时间 --30秒
      idle-timeout: 60000          #连接空闲时间 --1分钟
      max-lifetime: 300000         #连接生命周期，建议设置比数据库超时时长少30秒以上 --5分钟
      validation-timeout: 3000
      login-timeout: 5
      connection-test-query: SELECT 1
#  redis:
#    packages-to-scan: "com.manage.rbac"
#    expired-time: 3600
#    host: 127.0.0.1
#    port: 6379
#    password: 123456
#    timeout: 2000s
#    lettuce:
#      pool:
#        max-active: 100 #连接池最大连接数（使用负值表示没有限制）
#        max-idle: 10 #连接池中的最大空闲连接
#        min-idle: 5 #连接池中的最小空闲连接
#        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）

mybatis:
  mapper-locations: classpath*:mapper/**/**.xml
  type-aliases-package: com.manage.rbac.dao
  configuration:
    cache-enabled: true #使全局的映射器启用或禁用缓存
    lazy-loading-enabled: true #全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载
    aggressive-lazy-loading: true #当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载。
    multiple-result-sets-enabled: true #是否允许单条sql 返回多个数据集  (取决于驱动的兼容性) default:true
    use-column-label: true #是否可以使用列的别名 (取决于驱动的兼容性) default:true
    use-generated-keys: true #允许JDBC 生成主键。需要驱动器支持。如果设为了true，这个设置将强制使用被生成的主键，有一些驱动器不兼容不过仍然可以执行。  default:false
    auto-mapping-behavior: partial #指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射　PARTIAL:部分  FULL:全部
    default-executor-type: simple #这是默认的执行类型  （SIMPLE: 简单； REUSE: 执行器可能重复使用prepared statements语句；BATCH: 执行器可以重复执行语句和批量更新）
    map-underscore-to-camel-case: true #使用驼峰命名法转换字段。
    local-cache-scope: session #设置本地缓存范围 session:就会有数据的共享  statement:语句范围 (这样就不会有数据的共享 ) defalut:session
    jdbc-type-for-null: null #设置但JDBC类型为空时,某些驱动程序 要指定值,default:OTHER，插入空值时不需要指定类型