CREATE TABLE `finance_account` (
  `id` varchar(36) NOT NULL,
  `type` int(11) DEFAULT NULL COMMENT '类型 1-银行到款 2-手续费 3-清账余额',
  `comefrom` int(11) DEFAULT NULL COMMENT '来源 1-官网 2-自身 3-财务系统',
  `cust_no` varchar(40) DEFAULT NULL COMMENT '客户编码',
  `payment_type` int(11) DEFAULT NULL COMMENT '支付方式',
  `currency` varchar(20) DEFAULT 'RMB' COMMENT '货币单位，RMB',
  `amount` decimal(20,2) DEFAULT NULL COMMENT '记账金额',
  `pre_tax_amount` decimal(20,2) DEFAULT NULL COMMENT '税前金额',
  `tax_amount` decimal(20,2) DEFAULT NULL COMMENT '税金',
  `item_text` varchar(100) DEFAULT '' COMMENT '款项说明',
  `batch_id` varchar(40) DEFAULT '' COMMENT '批次号',
  `fiscal_year` varchar(10) DEFAULT '' COMMENT '会计年度',
  `company_code` varchar(30) DEFAULT '' COMMENT '公司Code',
  `document_number` varchar(50) DEFAULT '' COMMENT '凭证号',
  `doc_type` varchar(50) DEFAULT '' COMMENT '凭证类型,DZ-银行到款,DG-手续费,DB-清账余额,DA-调账,ZD-搬迁账',
  `document_date` date DEFAULT NULL COMMENT '凭证日期',
  `posting_date` date DEFAULT NULL COMMENT '过账日期',
  `need_certify` int(2) DEFAULT '0' COMMENT '是否需要申请凭证 0-否 1-是',
  `state` int(11) DEFAULT NULL COMMENT '状态 0-已提交 | 99-失败 | 100-成功',
  `clear_flag` int(11) DEFAULT '0' COMMENT '清账标识 0-未清 1-已清',
  `fail_info` varchar(200) DEFAULT '' COMMENT '失败信息',
  `invoke_time` datetime DEFAULT NULL COMMENT '调用时间',
  `rest_from` varchar(40) DEFAULT '' COMMENT '清账余额来自清账批次号',
  `remark` varchar(100) DEFAULT '' COMMENT '备注',
  `retry_count` int(11) DEFAULT '0' COMMENT '重试次数',
  `delete_flag` int(2) DEFAULT '0' COMMENT '是否被删除 0--否 1--是',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  `delete_by` varchar(30) DEFAULT '' COMMENT '删除人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_by` varchar(30) DEFAULT '' COMMENT '创建人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `update_by` varchar(30) DEFAULT '' COMMENT '更新人',
  PRIMARY KEY (`id`),
  UNIQUE KEY `udx_batch_idb_otdd` (`batch_id`),
  KEY `idx_cust_payment` (`cust_no`,`payment_type`),
  KEY `idx_number_year` (`document_number`,`fiscal_year`),
  KEY `idx_createtime` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='财务记账表';