package com.shop.dao.mapper;

import com.shop.model.pojo.OdSaleafter;
import com.shop.model.pojo.OdSaleafterExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface OdSaleafterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_saleafter
     *
     * @mbggenerated Tue May 17 18:25:38 CST 2016
     */
    int countByExample(OdSaleafterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_saleafter
     *
     * @mbggenerated Tue May 17 18:25:38 CST 2016
     */
    int deleteByExample(OdSaleafterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_saleafter
     *
     * @mbggenerated Tue May 17 18:25:38 CST 2016
     */
    @Delete({
        "delete from od_saleafter",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_saleafter
     *
     * @mbggenerated Tue May 17 18:25:38 CST 2016
     */
    @Insert({
        "insert into od_saleafter (order_id, order_amount, ",
        "cost_amount, product_id, ",
        "product_name, sku_num, ",
        "apply_time, user_id, ",
        "user_name, shop_id, ",
        "shop_name, refund_type, ",
        "refund_reason, saleafter_state, ",
        "deal_time, complete_time, ",
        "complain_id)",
        "values (#{orderId,jdbcType=VARCHAR}, #{orderAmount,jdbcType=BIGINT}, ",
        "#{costAmount,jdbcType=BIGINT}, #{productId,jdbcType=VARCHAR}, ",
        "#{productName,jdbcType=VARCHAR}, #{skuNum,jdbcType=VARCHAR}, ",
        "#{applyTime,jdbcType=TIMESTAMP}, #{userId,jdbcType=BIGINT}, ",
        "#{userName,jdbcType=VARCHAR}, #{shopId,jdbcType=BIGINT}, ",
        "#{shopName,jdbcType=VARCHAR}, #{refundType,jdbcType=INTEGER}, ",
        "#{refundReason,jdbcType=VARCHAR}, #{saleafterState,jdbcType=INTEGER}, ",
        "#{dealTime,jdbcType=TIMESTAMP}, #{completeTime,jdbcType=TIMESTAMP}, ",
        "#{complainId,jdbcType=BIGINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(OdSaleafter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_saleafter
     *
     * @mbggenerated Tue May 17 18:25:38 CST 2016
     */
    int insertSelective(OdSaleafter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_saleafter
     *
     * @mbggenerated Tue May 17 18:25:38 CST 2016
     */
    List<OdSaleafter> selectByExample(OdSaleafterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_saleafter
     *
     * @mbggenerated Tue May 17 18:25:38 CST 2016
     */
    @Select({
        "select",
        "id, order_id, order_amount, cost_amount, product_id, product_name, sku_num, ",
        "apply_time, user_id, user_name, shop_id, shop_name, refund_type, refund_reason, ",
        "saleafter_state, deal_time, complete_time, complain_id",
        "from od_saleafter",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    OdSaleafter selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_saleafter
     *
     * @mbggenerated Tue May 17 18:25:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") OdSaleafter record, @Param("example") OdSaleafterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_saleafter
     *
     * @mbggenerated Tue May 17 18:25:38 CST 2016
     */
    int updateByExample(@Param("record") OdSaleafter record, @Param("example") OdSaleafterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_saleafter
     *
     * @mbggenerated Tue May 17 18:25:38 CST 2016
     */
    int updateByPrimaryKeySelective(OdSaleafter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_saleafter
     *
     * @mbggenerated Tue May 17 18:25:38 CST 2016
     */
    @Update({
        "update od_saleafter",
        "set order_id = #{orderId,jdbcType=VARCHAR},",
          "order_amount = #{orderAmount,jdbcType=BIGINT},",
          "cost_amount = #{costAmount,jdbcType=BIGINT},",
          "product_id = #{productId,jdbcType=VARCHAR},",
          "product_name = #{productName,jdbcType=VARCHAR},",
          "sku_num = #{skuNum,jdbcType=VARCHAR},",
          "apply_time = #{applyTime,jdbcType=TIMESTAMP},",
          "user_id = #{userId,jdbcType=BIGINT},",
          "user_name = #{userName,jdbcType=VARCHAR},",
          "shop_id = #{shopId,jdbcType=BIGINT},",
          "shop_name = #{shopName,jdbcType=VARCHAR},",
          "refund_type = #{refundType,jdbcType=INTEGER},",
          "refund_reason = #{refundReason,jdbcType=VARCHAR},",
          "saleafter_state = #{saleafterState,jdbcType=INTEGER},",
          "deal_time = #{dealTime,jdbcType=TIMESTAMP},",
          "complete_time = #{completeTime,jdbcType=TIMESTAMP},",
          "complain_id = #{complainId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OdSaleafter record);
}