package com.shop.dao.mapper;

import com.shop.model.pojo.PdProduct;
import com.shop.model.pojo.PdProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface PdProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_product
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int countByExample(PdProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_product
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int deleteByExample(PdProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_product
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    @Delete({
        "delete from pd_product",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_product
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    @Insert({
        "insert into pd_product (product_id, shop_id, ",
        "name, title, direct_tag_id, ",
        "post_type, no_free, ",
        "imgs, max_buy, send_type, ",
        "send_address, send_province_id, ",
        "send_city_id, state, ",
        "update_time, updater, ",
        "create_time, creator, ",
        "note, type, send_time_limit, ",
        "delive_desc, is_customized, ",
        "audit_type, audit_time, ",
        "sale_time, offline_reason, ",
        "offline_time)",
        "values (#{productId,jdbcType=VARCHAR}, #{shopId,jdbcType=BIGINT}, ",
        "#{name,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, #{directTagId,jdbcType=INTEGER}, ",
        "#{postType,jdbcType=INTEGER}, #{noFree,jdbcType=VARCHAR}, ",
        "#{imgs,jdbcType=VARCHAR}, #{maxBuy,jdbcType=INTEGER}, #{sendType,jdbcType=INTEGER}, ",
        "#{sendAddress,jdbcType=VARCHAR}, #{sendProvinceId,jdbcType=INTEGER}, ",
        "#{sendCityId,jdbcType=INTEGER}, #{state,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{updater,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{creator,jdbcType=INTEGER}, ",
        "#{note,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, #{sendTimeLimit,jdbcType=INTEGER}, ",
        "#{deliveDesc,jdbcType=VARCHAR}, #{isCustomized,jdbcType=INTEGER}, ",
        "#{auditType,jdbcType=INTEGER}, #{auditTime,jdbcType=TIMESTAMP}, ",
        "#{saleTime,jdbcType=TIMESTAMP}, #{offlineReason,jdbcType=VARCHAR}, ",
        "#{offlineTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(PdProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_product
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int insertSelective(PdProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_product
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    List<PdProduct> selectByExample(PdProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_product
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    @Select({
        "select",
        "id, product_id, shop_id, name, title, direct_tag_id, post_type, no_free, imgs, ",
        "max_buy, send_type, send_address, send_province_id, send_city_id, state, update_time, ",
        "updater, create_time, creator, note, type, send_time_limit, delive_desc, is_customized, ",
        "audit_type, audit_time, sale_time, offline_reason, offline_time",
        "from pd_product",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    PdProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_product
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") PdProduct record, @Param("example") PdProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_product
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int updateByExample(@Param("record") PdProduct record, @Param("example") PdProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_product
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int updateByPrimaryKeySelective(PdProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_product
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    @Update({
        "update pd_product",
        "set product_id = #{productId,jdbcType=VARCHAR},",
          "shop_id = #{shopId,jdbcType=BIGINT},",
          "name = #{name,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "direct_tag_id = #{directTagId,jdbcType=INTEGER},",
          "post_type = #{postType,jdbcType=INTEGER},",
          "no_free = #{noFree,jdbcType=VARCHAR},",
          "imgs = #{imgs,jdbcType=VARCHAR},",
          "max_buy = #{maxBuy,jdbcType=INTEGER},",
          "send_type = #{sendType,jdbcType=INTEGER},",
          "send_address = #{sendAddress,jdbcType=VARCHAR},",
          "send_province_id = #{sendProvinceId,jdbcType=INTEGER},",
          "send_city_id = #{sendCityId,jdbcType=INTEGER},",
          "state = #{state,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "updater = #{updater,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=INTEGER},",
          "note = #{note,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "send_time_limit = #{sendTimeLimit,jdbcType=INTEGER},",
          "delive_desc = #{deliveDesc,jdbcType=VARCHAR},",
          "is_customized = #{isCustomized,jdbcType=INTEGER},",
          "audit_type = #{auditType,jdbcType=INTEGER},",
          "audit_time = #{auditTime,jdbcType=TIMESTAMP},",
          "sale_time = #{saleTime,jdbcType=TIMESTAMP},",
          "offline_reason = #{offlineReason,jdbcType=VARCHAR},",
          "offline_time = #{offlineTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PdProduct record);
}