package com.shop.dao.mapper;

import com.shop.model.pojo.PdSkuStock;
import com.shop.model.pojo.PdSkuStockExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface PdSkuStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_sku_stock
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int countByExample(PdSkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_sku_stock
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int deleteByExample(PdSkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_sku_stock
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    @Delete({
        "delete from pd_sku_stock",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_sku_stock
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    @Insert({
        "insert into pd_sku_stock (shop_id, product_id, ",
        "sku_num, sku_name, ",
        "cur_price, org_price, ",
        "stock_cnt, update_time, ",
        "updater, create_time, ",
        "creator, pic, note)",
        "values (#{shopId,jdbcType=BIGINT}, #{productId,jdbcType=VARCHAR}, ",
        "#{skuNum,jdbcType=VARCHAR}, #{skuName,jdbcType=VARCHAR}, ",
        "#{curPrice,jdbcType=BIGINT}, #{orgPrice,jdbcType=BIGINT}, ",
        "#{stockCnt,jdbcType=INTEGER}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{updater,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{creator,jdbcType=INTEGER}, #{pic,jdbcType=VARCHAR}, #{note,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(PdSkuStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_sku_stock
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int insertSelective(PdSkuStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_sku_stock
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    List<PdSkuStock> selectByExample(PdSkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_sku_stock
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    @Select({
        "select",
        "id, shop_id, product_id, sku_num, sku_name, cur_price, org_price, stock_cnt, ",
        "update_time, updater, create_time, creator, pic, note",
        "from pd_sku_stock",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    PdSkuStock selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_sku_stock
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") PdSkuStock record, @Param("example") PdSkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_sku_stock
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int updateByExample(@Param("record") PdSkuStock record, @Param("example") PdSkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_sku_stock
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int updateByPrimaryKeySelective(PdSkuStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_sku_stock
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    @Update({
        "update pd_sku_stock",
        "set shop_id = #{shopId,jdbcType=BIGINT},",
          "product_id = #{productId,jdbcType=VARCHAR},",
          "sku_num = #{skuNum,jdbcType=VARCHAR},",
          "sku_name = #{skuName,jdbcType=VARCHAR},",
          "cur_price = #{curPrice,jdbcType=BIGINT},",
          "org_price = #{orgPrice,jdbcType=BIGINT},",
          "stock_cnt = #{stockCnt,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "updater = #{updater,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=INTEGER},",
          "pic = #{pic,jdbcType=VARCHAR},",
          "note = #{note,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PdSkuStock record);
}