package com.shop.dao.mapper;

import com.shop.model.pojo.PdTag;
import com.shop.model.pojo.PdTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface PdTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_tag
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int countByExample(PdTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_tag
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int deleteByExample(PdTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_tag
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    @Delete({
        "delete from pd_tag",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_tag
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    @Insert({
        "insert into pd_tag (name, pid, ",
        "level, state, sort, ",
        "is_leaf, create_time, ",
        "creator, update_time, ",
        "updater, note)",
        "values (#{name,jdbcType=VARCHAR}, #{pid,jdbcType=INTEGER}, ",
        "#{level,jdbcType=INTEGER}, #{state,jdbcType=INTEGER}, #{sort,jdbcType=INTEGER}, ",
        "#{isLeaf,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{creator,jdbcType=INTEGER}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{updater,jdbcType=INTEGER}, #{note,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(PdTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_tag
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int insertSelective(PdTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_tag
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    List<PdTag> selectByExample(PdTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_tag
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    @Select({
        "select",
        "id, name, pid, level, state, sort, is_leaf, create_time, creator, update_time, ",
        "updater, note",
        "from pd_tag",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    PdTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_tag
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") PdTag record, @Param("example") PdTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_tag
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int updateByExample(@Param("record") PdTag record, @Param("example") PdTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_tag
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    int updateByPrimaryKeySelective(PdTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_tag
     *
     * @mbggenerated Fri May 13 11:32:38 CST 2016
     */
    @Update({
        "update pd_tag",
        "set name = #{name,jdbcType=VARCHAR},",
          "pid = #{pid,jdbcType=INTEGER},",
          "level = #{level,jdbcType=INTEGER},",
          "state = #{state,jdbcType=INTEGER},",
          "sort = #{sort,jdbcType=INTEGER},",
          "is_leaf = #{isLeaf,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "updater = #{updater,jdbcType=INTEGER},",
          "note = #{note,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PdTag record);
}