package com.shop.dao.mapper;

import com.shop.model.pojo.SysResource;
import com.shop.model.pojo.SysResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface SysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Apr 13 18:54:23 CST 2016
     */
    int countByExample(SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Apr 13 18:54:23 CST 2016
     */
    int deleteByExample(SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Apr 13 18:54:23 CST 2016
     */
    @Delete({
        "delete from sys_resource",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Apr 13 18:54:23 CST 2016
     */
    @Insert({
        "insert into sys_resource (name, path, ",
        "parent_id, is_show, ",
        "is_menu, tag)",
        "values (#{name,jdbcType=VARCHAR}, #{path,jdbcType=VARCHAR}, ",
        "#{parentId,jdbcType=INTEGER}, #{isShow,jdbcType=INTEGER}, ",
        "#{isMenu,jdbcType=INTEGER}, #{tag,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Apr 13 18:54:23 CST 2016
     */
    int insertSelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Apr 13 18:54:23 CST 2016
     */
    List<SysResource> selectByExample(SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Apr 13 18:54:23 CST 2016
     */
    @Select({
        "select",
        "id, name, path, parent_id, is_show, is_menu, tag",
        "from sys_resource",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    SysResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Apr 13 18:54:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysResource record, @Param("example") SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Apr 13 18:54:23 CST 2016
     */
    int updateByExample(@Param("record") SysResource record, @Param("example") SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Apr 13 18:54:23 CST 2016
     */
    int updateByPrimaryKeySelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Apr 13 18:54:23 CST 2016
     */
    @Update({
        "update sys_resource",
        "set name = #{name,jdbcType=VARCHAR},",
          "path = #{path,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=INTEGER},",
          "is_show = #{isShow,jdbcType=INTEGER},",
          "is_menu = #{isMenu,jdbcType=INTEGER},",
          "tag = #{tag,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SysResource record);
}