package com.db.dao.mapper;

import com.db.model.pojo.TbDb;
import com.db.model.pojo.TbDbExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TbDbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_db
     *
     * @mbggenerated Mon Dec 26 15:46:47 CST 2016
     */
    int countByExample(TbDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_db
     *
     * @mbggenerated Mon Dec 26 15:46:47 CST 2016
     */
    int deleteByExample(TbDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_db
     *
     * @mbggenerated Mon Dec 26 15:46:47 CST 2016
     */
    @Delete({
        "delete from tb_db",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_db
     *
     * @mbggenerated Mon Dec 26 15:46:47 CST 2016
     */
    @Insert({
        "insert into tb_db (ht, pt, ",
        "name, account, pwd, ",
        "create_time, update_time)",
        "values (#{ht,jdbcType=VARCHAR}, #{pt,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{account,jdbcType=VARCHAR}, #{pwd,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(TbDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_db
     *
     * @mbggenerated Mon Dec 26 15:46:47 CST 2016
     */
    int insertSelective(TbDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_db
     *
     * @mbggenerated Mon Dec 26 15:46:47 CST 2016
     */
    List<TbDb> selectByExample(TbDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_db
     *
     * @mbggenerated Mon Dec 26 15:46:47 CST 2016
     */
    @Select({
        "select",
        "id, ht, pt, name, account, pwd, create_time, update_time",
        "from tb_db",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TbDb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_db
     *
     * @mbggenerated Mon Dec 26 15:46:47 CST 2016
     */
    int updateByExampleSelective(@Param("record") TbDb record, @Param("example") TbDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_db
     *
     * @mbggenerated Mon Dec 26 15:46:47 CST 2016
     */
    int updateByExample(@Param("record") TbDb record, @Param("example") TbDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_db
     *
     * @mbggenerated Mon Dec 26 15:46:47 CST 2016
     */
    int updateByPrimaryKeySelective(TbDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_db
     *
     * @mbggenerated Mon Dec 26 15:46:47 CST 2016
     */
    @Update({
        "update tb_db",
        "set ht = #{ht,jdbcType=VARCHAR},",
          "pt = #{pt,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "account = #{account,jdbcType=VARCHAR},",
          "pwd = #{pwd,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TbDb record);
}