package com.manageplat.model.pojo;

import java.util.Date;

public class FileRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.id
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.name
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.type
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.path
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.size
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    private Long size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.create_time
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.link
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.source
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.note
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.id
     *
     * @return the value of file_record.id
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.id
     *
     * @param id the value for file_record.id
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.name
     *
     * @return the value of file_record.name
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.name
     *
     * @param name the value for file_record.name
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.type
     *
     * @return the value of file_record.type
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.type
     *
     * @param type the value for file_record.type
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.path
     *
     * @return the value of file_record.path
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.path
     *
     * @param path the value for file_record.path
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.size
     *
     * @return the value of file_record.size
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.size
     *
     * @param size the value for file_record.size
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.create_time
     *
     * @return the value of file_record.create_time
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.create_time
     *
     * @param createTime the value for file_record.create_time
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.link
     *
     * @return the value of file_record.link
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.link
     *
     * @param link the value for file_record.link
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.source
     *
     * @return the value of file_record.source
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.source
     *
     * @param source the value for file_record.source
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.note
     *
     * @return the value of file_record.note
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.note
     *
     * @param note the value for file_record.note
     *
     * @mbggenerated Thu Feb 09 11:42:00 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}