package com.shop.server.dao.mapper;

import com.shop.server.model.pojo.TbUu;
import com.shop.server.model.pojo.TbUuExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;

public interface TbUuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_uu
     *
     * @mbggenerated Wed Nov 15 00:34:19 CST 2017
     */
    int countByExample(TbUuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_uu
     *
     * @mbggenerated Wed Nov 15 00:34:19 CST 2017
     */
    int deleteByExample(TbUuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_uu
     *
     * @mbggenerated Wed Nov 15 00:34:19 CST 2017
     */
    @Insert({
        "insert into tb_uu (username)",
        "values (#{username,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=String.class)
    int insert(TbUu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_uu
     *
     * @mbggenerated Wed Nov 15 00:34:19 CST 2017
     */
    int insertSelective(TbUu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_uu
     *
     * @mbggenerated Wed Nov 15 00:34:19 CST 2017
     */
    List<TbUu> selectByExample(TbUuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_uu
     *
     * @mbggenerated Wed Nov 15 00:34:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbUu record, @Param("example") TbUuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_uu
     *
     * @mbggenerated Wed Nov 15 00:34:19 CST 2017
     */
    int updateByExample(@Param("record") TbUu record, @Param("example") TbUuExample example);
}