server:
  port: 8008

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15

#负载均衡
ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false

#actuator
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: ["health","info","beans","configprops","env","heapdump","threaddump","mappings","loggers","refresh"]

spring:
  application:
    name: micro-order
#数据库配置
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/micro_order?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 60000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

#mybatisplus插件
mybatis-plus:
  typeAliasesPackage: com.micro.order.model
  mapper-locations: classpath*:sqlmap/**/**.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: ignored
      logic-delete-value: 0
      logic-not-delete-value: 1
      table-prefix:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

#pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

#tcc事务
org:
    dromara:
         hmily :
            serializer : kryo
            recoverDelayTime : 128
            retryMax : 30
            scheduledDelay : 128
            scheduledThreadMax :  10
            repositorySupport : db
            started: false
            hmilyDbConfig :
                 driverClassName  : com.mysql.jdbc.Driver
                 url :  jdbc:mysql://localhost:3306/tcc?useUnicode=true&characterEncoding=utf8&useSSL=false
                 username : root
                 password : root