package com.manageplat.model.mapper;

import com.manageplat.model.pojo.FileRecord;
import com.manageplat.model.pojo.FileRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface FileRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Tue Jul 28 16:48:10 CST 2015
     */
    int countByExample(FileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Tue Jul 28 16:48:10 CST 2015
     */
    int deleteByExample(FileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Tue Jul 28 16:48:10 CST 2015
     */
    @Delete({
        "delete from file_record",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Tue Jul 28 16:48:10 CST 2015
     */
    @Insert({
        "insert into file_record (create_time, type, ",
        "url, link)",
        "values (#{createTime,jdbcType=TIMESTAMP}, #{type,jdbcType=INTEGER}, ",
        "#{url,jdbcType=VARCHAR}, #{link,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(FileRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Tue Jul 28 16:48:10 CST 2015
     */
    int insertSelective(FileRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Tue Jul 28 16:48:10 CST 2015
     */
    List<FileRecord> selectByExample(FileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Tue Jul 28 16:48:10 CST 2015
     */
    @Select({
        "select",
        "id, create_time, type, url, link",
        "from file_record",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    FileRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Tue Jul 28 16:48:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") FileRecord record, @Param("example") FileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Tue Jul 28 16:48:10 CST 2015
     */
    int updateByExample(@Param("record") FileRecord record, @Param("example") FileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Tue Jul 28 16:48:10 CST 2015
     */
    int updateByPrimaryKeySelective(FileRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Tue Jul 28 16:48:10 CST 2015
     */
    @Update({
        "update file_record",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "type = #{type,jdbcType=INTEGER},",
          "url = #{url,jdbcType=VARCHAR},",
          "link = #{link,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(FileRecord record);
}