package com.manageplat.model.mapper;

import com.manageplat.model.pojo.TyEntityCdn;
import com.manageplat.model.pojo.TyEntityCdnExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TyEntityCdnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity_cdn
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    int countByExample(TyEntityCdnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity_cdn
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    int deleteByExample(TyEntityCdnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity_cdn
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    @Delete({
        "delete from ty_entity_cdn",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity_cdn
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    @Insert({
        "insert into ty_entity_cdn (entity_id, cdn_name, ",
        "cdn_col, cdn_type, ",
        "is_show, sort)",
        "values (#{entityId,jdbcType=INTEGER}, #{cdnName,jdbcType=VARCHAR}, ",
        "#{cdnCol,jdbcType=VARCHAR}, #{cdnType,jdbcType=INTEGER}, ",
        "#{isShow,jdbcType=INTEGER}, #{sort,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(TyEntityCdn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity_cdn
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    int insertSelective(TyEntityCdn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity_cdn
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    List<TyEntityCdn> selectByExample(TyEntityCdnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity_cdn
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    @Select({
        "select",
        "id, entity_id, cdn_name, cdn_col, cdn_type, is_show, sort",
        "from ty_entity_cdn",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TyEntityCdn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity_cdn
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") TyEntityCdn record, @Param("example") TyEntityCdnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity_cdn
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    int updateByExample(@Param("record") TyEntityCdn record, @Param("example") TyEntityCdnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity_cdn
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    int updateByPrimaryKeySelective(TyEntityCdn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity_cdn
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    @Update({
        "update ty_entity_cdn",
        "set entity_id = #{entityId,jdbcType=INTEGER},",
          "cdn_name = #{cdnName,jdbcType=VARCHAR},",
          "cdn_col = #{cdnCol,jdbcType=VARCHAR},",
          "cdn_type = #{cdnType,jdbcType=INTEGER},",
          "is_show = #{isShow,jdbcType=INTEGER},",
          "sort = #{sort,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TyEntityCdn record);
}