package com.manageplat.model.mapper;

import com.manageplat.model.pojo.UserActNote;
import com.manageplat.model.pojo.UserActNoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface UserActNoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_act_note
     *
     * @mbggenerated Sat Jun 27 16:01:41 CST 2015
     */
    int countByExample(UserActNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_act_note
     *
     * @mbggenerated Sat Jun 27 16:01:41 CST 2015
     */
    int deleteByExample(UserActNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_act_note
     *
     * @mbggenerated Sat Jun 27 16:01:41 CST 2015
     */
    @Delete({
        "delete from user_act_note",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_act_note
     *
     * @mbggenerated Sat Jun 27 16:01:41 CST 2015
     */
    @Insert({
        "insert into user_act_note (name, name_ch)",
        "values (#{name,jdbcType=VARCHAR}, #{nameCh,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(UserActNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_act_note
     *
     * @mbggenerated Sat Jun 27 16:01:41 CST 2015
     */
    int insertSelective(UserActNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_act_note
     *
     * @mbggenerated Sat Jun 27 16:01:41 CST 2015
     */
    List<UserActNote> selectByExample(UserActNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_act_note
     *
     * @mbggenerated Sat Jun 27 16:01:41 CST 2015
     */
    @Select({
        "select",
        "id, name, name_ch",
        "from user_act_note",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    UserActNote selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_act_note
     *
     * @mbggenerated Sat Jun 27 16:01:41 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserActNote record, @Param("example") UserActNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_act_note
     *
     * @mbggenerated Sat Jun 27 16:01:41 CST 2015
     */
    int updateByExample(@Param("record") UserActNote record, @Param("example") UserActNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_act_note
     *
     * @mbggenerated Sat Jun 27 16:01:41 CST 2015
     */
    int updateByPrimaryKeySelective(UserActNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_act_note
     *
     * @mbggenerated Sat Jun 27 16:01:41 CST 2015
     */
    @Update({
        "update user_act_note",
        "set name = #{name,jdbcType=VARCHAR},",
          "name_ch = #{nameCh,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserActNote record);
}