package com.manageplat.model.mapper;

import com.manageplat.model.pojo.TyEntity;
import com.manageplat.model.pojo.TyEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TyEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    int countByExample(TyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    int deleteByExample(TyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    @Delete({
        "delete from ty_entity",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    @Insert({
        "insert into ty_entity (name, table_name, ",
        "query_sql, page_size)",
        "values (#{name,jdbcType=VARCHAR}, #{tableName,jdbcType=VARCHAR}, ",
        "#{querySql,jdbcType=VARCHAR}, #{pageSize,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(TyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    int insertSelective(TyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    List<TyEntity> selectByExample(TyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    @Select({
        "select",
        "id, name, table_name, query_sql, page_size",
        "from ty_entity",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TyEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") TyEntity record, @Param("example") TyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    int updateByExample(@Param("record") TyEntity record, @Param("example") TyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    int updateByPrimaryKeySelective(TyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_entity
     *
     * @mbggenerated Fri Sep 18 15:50:53 CST 2015
     */
    @Update({
        "update ty_entity",
        "set name = #{name,jdbcType=VARCHAR},",
          "table_name = #{tableName,jdbcType=VARCHAR},",
          "query_sql = #{querySql,jdbcType=VARCHAR},",
          "page_size = #{pageSize,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TyEntity record);
}