package com.shop.user.dao.mapper;

import com.shop.user.model.pojo.ShopUser;
import com.shop.user.model.pojo.ShopUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ShopUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Sun Dec 17 16:10:34 CST 2017
     */
    int countByExample(ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Sun Dec 17 16:10:34 CST 2017
     */
    int deleteByExample(ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Sun Dec 17 16:10:34 CST 2017
     */
    @Delete({
        "delete from shop_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Sun Dec 17 16:10:34 CST 2017
     */
    @Insert({
        "insert into shop_user (name, nick_name, ",
        "sex, mobile, statu, ",
        "reg_comefrom, reg_time, ",
        "last_login_time, token, ",
        "token_expire_time, create_time, ",
        "modified_time)",
        "values (#{name,jdbcType=VARCHAR}, #{nickName,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=INTEGER}, #{mobile,jdbcType=VARCHAR}, #{statu,jdbcType=INTEGER}, ",
        "#{regComefrom,jdbcType=INTEGER}, #{regTime,jdbcType=TIMESTAMP}, ",
        "#{lastLoginTime,jdbcType=TIMESTAMP}, #{token,jdbcType=VARCHAR}, ",
        "#{tokenExpireTime,jdbcType=TIMESTAMP}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{modifiedTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ShopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Sun Dec 17 16:10:34 CST 2017
     */
    int insertSelective(ShopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Sun Dec 17 16:10:34 CST 2017
     */
    List<ShopUser> selectByExample(ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Sun Dec 17 16:10:34 CST 2017
     */
    @Select({
        "select",
        "id, name, nick_name, sex, mobile, statu, reg_comefrom, reg_time, last_login_time, ",
        "token, token_expire_time, create_time, modified_time",
        "from shop_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    ShopUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Sun Dec 17 16:10:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") ShopUser record, @Param("example") ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Sun Dec 17 16:10:34 CST 2017
     */
    int updateByExample(@Param("record") ShopUser record, @Param("example") ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Sun Dec 17 16:10:34 CST 2017
     */
    int updateByPrimaryKeySelective(ShopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbggenerated Sun Dec 17 16:10:34 CST 2017
     */
    @Update({
        "update shop_user",
        "set name = #{name,jdbcType=VARCHAR},",
          "nick_name = #{nickName,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=INTEGER},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "statu = #{statu,jdbcType=INTEGER},",
          "reg_comefrom = #{regComefrom,jdbcType=INTEGER},",
          "reg_time = #{regTime,jdbcType=TIMESTAMP},",
          "last_login_time = #{lastLoginTime,jdbcType=TIMESTAMP},",
          "token = #{token,jdbcType=VARCHAR},",
          "token_expire_time = #{tokenExpireTime,jdbcType=TIMESTAMP},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modified_time = #{modifiedTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ShopUser record);
}