package com.otd.boot.finance.dao.mapper;

import com.otd.boot.finance.model.entity.FinanceAccount;
import com.otd.boot.finance.model.entity.FinanceAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface FinanceAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_account
     *
     * @mbggenerated Tue Feb 20 12:41:03 CST 2024
     */
    int countByExample(FinanceAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_account
     *
     * @mbggenerated Tue Feb 20 12:41:03 CST 2024
     */
    int deleteByExample(FinanceAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_account
     *
     * @mbggenerated Tue Feb 20 12:41:03 CST 2024
     */
    @Delete({
        "delete from finance_account",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_account
     *
     * @mbggenerated Tue Feb 20 12:41:03 CST 2024
     */
    @Insert({
        "insert into finance_account (id, type, ",
        "comefrom, cust_no, ",
        "payment_type, currency, ",
        "amount, pre_tax_amount, ",
        "tax_amount, item_text, ",
        "batch_id, fiscal_year, ",
        "company_code, document_number, ",
        "doc_type, document_date, ",
        "posting_date, need_certify, ",
        "state, clear_flag, ",
        "fail_info, invoke_time, ",
        "rest_from, remark, ",
        "retry_count, delete_flag, ",
        "delete_time, delete_by, ",
        "create_time, create_by, ",
        "update_time, update_by)",
        "values (#{id,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, ",
        "#{comefrom,jdbcType=INTEGER}, #{custNo,jdbcType=VARCHAR}, ",
        "#{paymentType,jdbcType=INTEGER}, #{currency,jdbcType=VARCHAR}, ",
        "#{amount,jdbcType=DECIMAL}, #{preTaxAmount,jdbcType=DECIMAL}, ",
        "#{taxAmount,jdbcType=DECIMAL}, #{itemText,jdbcType=VARCHAR}, ",
        "#{batchId,jdbcType=VARCHAR}, #{fiscalYear,jdbcType=VARCHAR}, ",
        "#{companyCode,jdbcType=VARCHAR}, #{documentNumber,jdbcType=VARCHAR}, ",
        "#{docType,jdbcType=VARCHAR}, #{documentDate,jdbcType=DATE}, ",
        "#{postingDate,jdbcType=DATE}, #{needCertify,jdbcType=INTEGER}, ",
        "#{state,jdbcType=INTEGER}, #{clearFlag,jdbcType=INTEGER}, ",
        "#{failInfo,jdbcType=VARCHAR}, #{invokeTime,jdbcType=TIMESTAMP}, ",
        "#{restFrom,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{retryCount,jdbcType=INTEGER}, #{deleteFlag,jdbcType=INTEGER}, ",
        "#{deleteTime,jdbcType=TIMESTAMP}, #{deleteBy,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createBy,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{updateBy,jdbcType=VARCHAR})"
    })
    int insert(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_account
     *
     * @mbggenerated Tue Feb 20 12:41:03 CST 2024
     */
    int insertSelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_account
     *
     * @mbggenerated Tue Feb 20 12:41:03 CST 2024
     */
    List<FinanceAccount> selectByExample(FinanceAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_account
     *
     * @mbggenerated Tue Feb 20 12:41:03 CST 2024
     */
    @Select({
        "select",
        "id, type, comefrom, cust_no, payment_type, currency, amount, pre_tax_amount, ",
        "tax_amount, item_text, batch_id, fiscal_year, company_code, document_number, ",
        "doc_type, document_date, posting_date, need_certify, state, clear_flag, fail_info, ",
        "invoke_time, rest_from, remark, retry_count, delete_flag, delete_time, delete_by, ",
        "create_time, create_by, update_time, update_by",
        "from finance_account",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    FinanceAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_account
     *
     * @mbggenerated Tue Feb 20 12:41:03 CST 2024
     */
    int updateByExampleSelective(@Param("record") FinanceAccount record, @Param("example") FinanceAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_account
     *
     * @mbggenerated Tue Feb 20 12:41:03 CST 2024
     */
    int updateByExample(@Param("record") FinanceAccount record, @Param("example") FinanceAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_account
     *
     * @mbggenerated Tue Feb 20 12:41:03 CST 2024
     */
    int updateByPrimaryKeySelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_account
     *
     * @mbggenerated Tue Feb 20 12:41:03 CST 2024
     */
    @Update({
        "update finance_account",
        "set type = #{type,jdbcType=INTEGER},",
          "comefrom = #{comefrom,jdbcType=INTEGER},",
          "cust_no = #{custNo,jdbcType=VARCHAR},",
          "payment_type = #{paymentType,jdbcType=INTEGER},",
          "currency = #{currency,jdbcType=VARCHAR},",
          "amount = #{amount,jdbcType=DECIMAL},",
          "pre_tax_amount = #{preTaxAmount,jdbcType=DECIMAL},",
          "tax_amount = #{taxAmount,jdbcType=DECIMAL},",
          "item_text = #{itemText,jdbcType=VARCHAR},",
          "batch_id = #{batchId,jdbcType=VARCHAR},",
          "fiscal_year = #{fiscalYear,jdbcType=VARCHAR},",
          "company_code = #{companyCode,jdbcType=VARCHAR},",
          "document_number = #{documentNumber,jdbcType=VARCHAR},",
          "doc_type = #{docType,jdbcType=VARCHAR},",
          "document_date = #{documentDate,jdbcType=DATE},",
          "posting_date = #{postingDate,jdbcType=DATE},",
          "need_certify = #{needCertify,jdbcType=INTEGER},",
          "state = #{state,jdbcType=INTEGER},",
          "clear_flag = #{clearFlag,jdbcType=INTEGER},",
          "fail_info = #{failInfo,jdbcType=VARCHAR},",
          "invoke_time = #{invokeTime,jdbcType=TIMESTAMP},",
          "rest_from = #{restFrom,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "retry_count = #{retryCount,jdbcType=INTEGER},",
          "delete_flag = #{deleteFlag,jdbcType=INTEGER},",
          "delete_time = #{deleteTime,jdbcType=TIMESTAMP},",
          "delete_by = #{deleteBy,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_by = #{createBy,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(FinanceAccount record);
}