server:
  port: 8007

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15


spring:
  application:
    name: micro-course
#数据库配置
  datasource:
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      url: ${spring.datasource.url}
      type: ${spring.datasource.type}
      initialSize: ${spring.datasource.initialSize}
      minIdle: ${spring.datasource.minIdle}
      maxActive: ${spring.datasource.maxActive}
      maxWait: ${spring.datasource.maxWait}
      timeBetweenEvictionRunsMillis: ${spring.datasource.timeBetweenEvictionRunsMillis}
      minEvictableIdleTimeMillis: ${spring.datasource.minEvictableIdleTimeMillis}
      validationQuery: ${spring.datasource.validationQuery}
      testWhileIdle: ${spring.datasource.testWhileIdle}
      testOnBorrow: ${spring.datasource.testOnBorrow}
      testOnReturn: ${spring.datasource.testOnReturn}

#mybatisplus插件
mybatis-plus:
  typeAliasesPackage: com.micro.course.model
  mapper-locations: classpath*:sqlmap/**/**.xml
  global-config:
    db-config:
      id-type: 0
      field-strategy: ignored
      logic-delete-value: 0
      logic-not-delete-value: 1
      table-prefix:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

#pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
