package com.otd.boot.plat.dao.mapper;

import com.otd.boot.plat.model.entity.Factory;
import com.otd.boot.plat.model.entity.FactoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface FactoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    int countByExample(FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    int deleteByExample(FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    @Delete({
        "delete from factory",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    @Insert({
        "insert into factory (factory_no, factory_name, ",
        "factory_address, legal_person, ",
        "create_time, create_by, ",
        "update_time, update_by)",
        "values (#{factoryNo,jdbcType=VARCHAR}, #{factoryName,jdbcType=VARCHAR}, ",
        "#{factoryAddress,jdbcType=VARCHAR}, #{legalPerson,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createBy,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{updateBy,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    int insertSelective(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    List<Factory> selectByExample(FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    @Select({
        "select",
        "id, factory_no, factory_name, factory_address, legal_person, create_time, create_by, ",
        "update_time, update_by",
        "from factory",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Factory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    int updateByExampleSelective(@Param("record") Factory record, @Param("example") FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    int updateByExample(@Param("record") Factory record, @Param("example") FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    int updateByPrimaryKeySelective(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbggenerated Wed Feb 28 16:57:37 CST 2024
     */
    @Update({
        "update factory",
        "set factory_no = #{factoryNo,jdbcType=VARCHAR},",
          "factory_name = #{factoryName,jdbcType=VARCHAR},",
          "factory_address = #{factoryAddress,jdbcType=VARCHAR},",
          "legal_person = #{legalPerson,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_by = #{createBy,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Factory record);
}