package com.otd.boot.plat.dao.mapper;

import com.otd.boot.plat.model.entity.LogisticsProvider;
import com.otd.boot.plat.model.entity.LogisticsProviderExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface LogisticsProviderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_provider
     *
     * @mbggenerated Thu Feb 29 17:33:27 CST 2024
     */
    int countByExample(LogisticsProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_provider
     *
     * @mbggenerated Thu Feb 29 17:33:27 CST 2024
     */
    int deleteByExample(LogisticsProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_provider
     *
     * @mbggenerated Thu Feb 29 17:33:27 CST 2024
     */
    @Delete({
        "delete from logistics_provider",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_provider
     *
     * @mbggenerated Thu Feb 29 17:33:27 CST 2024
     */
    @Insert({
        "insert into logistics_provider (logistics_provider_no, logistics_provider_name, ",
        "express_type, first_weight, ",
        "create_time, create_by, ",
        "update_time, update_by)",
        "values (#{logisticsProviderNo,jdbcType=VARCHAR}, #{logisticsProviderName,jdbcType=VARCHAR}, ",
        "#{expressType,jdbcType=VARCHAR}, #{firstWeight,jdbcType=DECIMAL}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createBy,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{updateBy,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(LogisticsProvider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_provider
     *
     * @mbggenerated Thu Feb 29 17:33:27 CST 2024
     */
    int insertSelective(LogisticsProvider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_provider
     *
     * @mbggenerated Thu Feb 29 17:33:27 CST 2024
     */
    List<LogisticsProvider> selectByExample(LogisticsProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_provider
     *
     * @mbggenerated Thu Feb 29 17:33:27 CST 2024
     */
    @Select({
        "select",
        "id, logistics_provider_no, logistics_provider_name, express_type, first_weight, ",
        "create_time, create_by, update_time, update_by",
        "from logistics_provider",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    LogisticsProvider selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_provider
     *
     * @mbggenerated Thu Feb 29 17:33:27 CST 2024
     */
    int updateByExampleSelective(@Param("record") LogisticsProvider record, @Param("example") LogisticsProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_provider
     *
     * @mbggenerated Thu Feb 29 17:33:27 CST 2024
     */
    int updateByExample(@Param("record") LogisticsProvider record, @Param("example") LogisticsProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_provider
     *
     * @mbggenerated Thu Feb 29 17:33:27 CST 2024
     */
    int updateByPrimaryKeySelective(LogisticsProvider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_provider
     *
     * @mbggenerated Thu Feb 29 17:33:27 CST 2024
     */
    @Update({
        "update logistics_provider",
        "set logistics_provider_no = #{logisticsProviderNo,jdbcType=VARCHAR},",
          "logistics_provider_name = #{logisticsProviderName,jdbcType=VARCHAR},",
          "express_type = #{expressType,jdbcType=VARCHAR},",
          "first_weight = #{firstWeight,jdbcType=DECIMAL},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_by = #{createBy,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(LogisticsProvider record);
}