package com.otd.boot.plat.dao.mapper;

import com.otd.boot.plat.model.entity.Storage;
import com.otd.boot.plat.model.entity.StorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface StorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated Thu Feb 29 18:04:23 CST 2024
     */
    int countByExample(StorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated Thu Feb 29 18:04:23 CST 2024
     */
    int deleteByExample(StorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated Thu Feb 29 18:04:23 CST 2024
     */
    @Delete({
        "delete from storage",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated Thu Feb 29 18:04:23 CST 2024
     */
    @Insert({
        "insert into storage (storage_code, storage_name, ",
        "storage_type, storage_manager, ",
        "warehouse_code, contact_tel, ",
        "province_code, province_name, ",
        "city_code, city_name, ",
        "county_code, county_name, ",
        "address, remark, ",
        "create_time, create_by, ",
        "update_time, update_by)",
        "values (#{storageCode,jdbcType=VARCHAR}, #{storageName,jdbcType=VARCHAR}, ",
        "#{storageType,jdbcType=INTEGER}, #{storageManager,jdbcType=VARCHAR}, ",
        "#{warehouseCode,jdbcType=VARCHAR}, #{contactTel,jdbcType=VARCHAR}, ",
        "#{provinceCode,jdbcType=VARCHAR}, #{provinceName,jdbcType=VARCHAR}, ",
        "#{cityCode,jdbcType=VARCHAR}, #{cityName,jdbcType=VARCHAR}, ",
        "#{countyCode,jdbcType=VARCHAR}, #{countyName,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createBy,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{updateBy,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated Thu Feb 29 18:04:23 CST 2024
     */
    int insertSelective(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated Thu Feb 29 18:04:23 CST 2024
     */
    List<Storage> selectByExample(StorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated Thu Feb 29 18:04:23 CST 2024
     */
    @Select({
        "select",
        "id, storage_code, storage_name, storage_type, storage_manager, warehouse_code, ",
        "contact_tel, province_code, province_name, city_code, city_name, county_code, ",
        "county_name, address, remark, create_time, create_by, update_time, update_by",
        "from storage",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Storage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated Thu Feb 29 18:04:23 CST 2024
     */
    int updateByExampleSelective(@Param("record") Storage record, @Param("example") StorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated Thu Feb 29 18:04:23 CST 2024
     */
    int updateByExample(@Param("record") Storage record, @Param("example") StorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated Thu Feb 29 18:04:23 CST 2024
     */
    int updateByPrimaryKeySelective(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbggenerated Thu Feb 29 18:04:23 CST 2024
     */
    @Update({
        "update storage",
        "set storage_code = #{storageCode,jdbcType=VARCHAR},",
          "storage_name = #{storageName,jdbcType=VARCHAR},",
          "storage_type = #{storageType,jdbcType=INTEGER},",
          "storage_manager = #{storageManager,jdbcType=VARCHAR},",
          "warehouse_code = #{warehouseCode,jdbcType=VARCHAR},",
          "contact_tel = #{contactTel,jdbcType=VARCHAR},",
          "province_code = #{provinceCode,jdbcType=VARCHAR},",
          "province_name = #{provinceName,jdbcType=VARCHAR},",
          "city_code = #{cityCode,jdbcType=VARCHAR},",
          "city_name = #{cityName,jdbcType=VARCHAR},",
          "county_code = #{countyCode,jdbcType=VARCHAR},",
          "county_name = #{countyName,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_by = #{createBy,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Storage record);
}