package com.otd.boot.plat.dao.mapper;

import com.otd.boot.plat.model.entity.Warehouse;
import com.otd.boot.plat.model.entity.WarehouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface WarehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Wed Feb 28 17:49:27 CST 2024
     */
    int countByExample(WarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Wed Feb 28 17:49:27 CST 2024
     */
    int deleteByExample(WarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Wed Feb 28 17:49:27 CST 2024
     */
    @Delete({
        "delete from warehouse",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Wed Feb 28 17:49:27 CST 2024
     */
    @Insert({
        "insert into warehouse (warehouse_code, warehouse_name, ",
        "is_enable, address, ",
        "contact_person, contact_tel, ",
        "contact_email, logistics_provider_no, ",
        "diy_capacity, vkorgs, ",
        "line_body_qps, work_start_time, ",
        "work_end_time, in_warehouse_time, ",
        "legal_person, create_time, ",
        "create_by, update_time, ",
        "update_by)",
        "values (#{warehouseCode,jdbcType=VARCHAR}, #{warehouseName,jdbcType=VARCHAR}, ",
        "#{isEnable,jdbcType=INTEGER}, #{address,jdbcType=VARCHAR}, ",
        "#{contactPerson,jdbcType=VARCHAR}, #{contactTel,jdbcType=VARCHAR}, ",
        "#{contactEmail,jdbcType=VARCHAR}, #{logisticsProviderNo,jdbcType=VARCHAR}, ",
        "#{diyCapacity,jdbcType=INTEGER}, #{vkorgs,jdbcType=VARCHAR}, ",
        "#{lineBodyQps,jdbcType=INTEGER}, #{workStartTime,jdbcType=VARCHAR}, ",
        "#{workEndTime,jdbcType=VARCHAR}, #{inWarehouseTime,jdbcType=DECIMAL}, ",
        "#{legalPerson,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{createBy,jdbcType=VARCHAR}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{updateBy,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Warehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Wed Feb 28 17:49:27 CST 2024
     */
    int insertSelective(Warehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Wed Feb 28 17:49:27 CST 2024
     */
    List<Warehouse> selectByExample(WarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Wed Feb 28 17:49:27 CST 2024
     */
    @Select({
        "select",
        "id, warehouse_code, warehouse_name, is_enable, address, contact_person, contact_tel, ",
        "contact_email, logistics_provider_no, diy_capacity, vkorgs, line_body_qps, work_start_time, ",
        "work_end_time, in_warehouse_time, legal_person, create_time, create_by, update_time, ",
        "update_by",
        "from warehouse",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Warehouse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Wed Feb 28 17:49:27 CST 2024
     */
    int updateByExampleSelective(@Param("record") Warehouse record, @Param("example") WarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Wed Feb 28 17:49:27 CST 2024
     */
    int updateByExample(@Param("record") Warehouse record, @Param("example") WarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Wed Feb 28 17:49:27 CST 2024
     */
    int updateByPrimaryKeySelective(Warehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Wed Feb 28 17:49:27 CST 2024
     */
    @Update({
        "update warehouse",
        "set warehouse_code = #{warehouseCode,jdbcType=VARCHAR},",
          "warehouse_name = #{warehouseName,jdbcType=VARCHAR},",
          "is_enable = #{isEnable,jdbcType=INTEGER},",
          "address = #{address,jdbcType=VARCHAR},",
          "contact_person = #{contactPerson,jdbcType=VARCHAR},",
          "contact_tel = #{contactTel,jdbcType=VARCHAR},",
          "contact_email = #{contactEmail,jdbcType=VARCHAR},",
          "logistics_provider_no = #{logisticsProviderNo,jdbcType=VARCHAR},",
          "diy_capacity = #{diyCapacity,jdbcType=INTEGER},",
          "vkorgs = #{vkorgs,jdbcType=VARCHAR},",
          "line_body_qps = #{lineBodyQps,jdbcType=INTEGER},",
          "work_start_time = #{workStartTime,jdbcType=VARCHAR},",
          "work_end_time = #{workEndTime,jdbcType=VARCHAR},",
          "in_warehouse_time = #{inWarehouseTime,jdbcType=DECIMAL},",
          "legal_person = #{legalPerson,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_by = #{createBy,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Warehouse record);
}